// 現在完了とその周辺（8つの型・40文）
// 診断で崩れていた「〜している/していた を全部 be+ing にする」を型で切り分ける。
// 文はそのまま暗記して使える形にしてある（仕事で言い換えやすい主語・動詞を選択）。
// o[0] が必ず正解。表示時にシャッフルする。誤答には診断で実際に選んだ答えを入れている。

const KTYPES=[
  {id:"keep",name:"前から今まで続いている",form:"have + 過去分詞",cue:"for / since",
   core:"「3年間ずっと」「先週から」のように期間が付いたら、今この瞬間の話ではなく前から今まで。ing にしない。",
   ng:"am living / am knowing（期間が付いているのに進行形にする）"},
  {id:"exp",name:"やったことがある（経験）",form:"have + 過去分詞",cue:"once / ever / never / before / 〜回",
   core:"経験が今の自分にあるかどうかの話。いつやったかは言わない。",
   ng:"went（過去形にする。それだと「いつ行ったか」の話になる）"},
  {id:"done",name:"もう終わった（今もその状態）",form:"have + 過去分詞",cue:"already / just / yet",
   core:"終わった結果が今に効いている。「もう出発した→だから今ここにいない」。",
   ng:"already left（過去形にすると今との繋がりが消える）"},
  {id:"past",name:"いつを言うなら過去形",form:"過去形",cue:"last year / yesterday / 〜ago / in 2020",
   core:"「いつ」が文の中にあるなら過去形。have + 過去分詞と同じ文には入れられない。",
   ng:"have been to Kyoto last year（いつ＋完了は同居できない）"},
  {id:"now",name:"今この瞬間だけ",form:"am / is / are + ing",cue:"now / 期間の言葉がない",
   core:"目の前で起きている最中だけが進行形。know・want・have のような状態は ing にしない。",
   ng:"am knowing / am having（状態を進行形にする）"},
  {id:"keepdo",name:"ずっとやり続けている",form:"have been + ing",cue:"for / since ＋ 動きのある動詞",
   core:"期間が付いて、しかも動作が続いている。live や know のような状態ではなく play・wait・rain。",
   ng:"is playing for two hours（期間が付いているのに進行形だけで済ませる）"},
  {id:"before2",name:"過去のある時点より前",form:"had + 過去分詞",cue:"when 〜 / before 〜（過去の基準点）",
   core:"過去の出来事が2つあって順番を示したいとき、先に起きた方を had にする。",
   ng:"was already leaving / has already left（基準が今のままになっている）"},
  {id:"regret",name:"あの時こうすべきだった",form:"助動詞 + have + 過去分詞",cue:"should / must / cannot / may",
   core:"have + 過去分詞を助動詞の後ろに置くと「もう終わったこと」への判断になる。",
   ng:"should go / must be（今の話になってしまう）"},
];

const KSENTS=[
  // ===== keep: 前から今まで続いている（状態） =====
  {id:1,t:"keep",jp:"私は3年間ずっと東京に住んでいる。",en:"I have lived in Tokyo for three years.",
   blank:"have lived",o:["have lived","am living","live","was living"],cue:"for three years",
   why:"for three years（3年間）があるので、今この瞬間の話ではなく前から今まで。ing は使わない。"},
  {id:2,t:"keep",jp:"私は2020年から彼を知っている。",en:"I have known him since 2020.",
   blank:"have known",o:["have known","am knowing","know","have been knowing"],cue:"since 2020",
   why:"since 2020（2020年から）があるので続いている形。know は状態なので ing にしない（have been knowing は誤り）。"},
  {id:3,t:"keep",jp:"先週からずっと忙しい。",en:"We have been busy since last week.",
   blank:"have been",o:["have been","are being","were","have being"],cue:"since last week",
   why:"忙しい状態が先週から今まで続いている。be動詞の過去分詞は been。"},
  {id:4,t:"keep",jp:"彼は10年間ここで働いている。",en:"He has worked here for ten years.",
   blank:"has worked",o:["has worked","is working","works","has been work"],cue:"for ten years",
   why:"主語が He なので has。for ten years があるので現在形 works では足りない。"},
  {id:5,t:"keep",jp:"この車をもう5年持っている。",en:"I have had this car for five years.",
   blank:"have had",o:["have had","am having","have","had"],cue:"for five years",
   why:"have（持っている）の過去分詞も had。have had と重なるのが気持ち悪いが、これが正しい形。"},

  // ===== exp: やったことがある（経験） =====
  {id:6,t:"exp",jp:"私は一度、京都に行ったことがある。",en:"I have been to Kyoto once.",
   blank:"have been",o:["have been","went","have gone","was"],cue:"once",
   why:"経験の話なので have been to。went だと「いつ行ったか」の報告になる。have gone to は「行ってしまって今いない」。"},
  {id:7,t:"exp",jp:"納豆を食べたことある？",en:"Have you ever eaten natto?",
   blank:"Have you ever eaten",o:["Have you ever eaten","Did you ever eat","Have you ever ate","Are you ever eating"],cue:"ever",
   why:"ever（今までに）が経験の合図。eat の過去分詞は eaten（ate は過去形）。"},
  {id:8,t:"exp",jp:"こんな大きな犬は見たことがない。",en:"I have never seen such a big dog.",
   blank:"have never seen",o:["have never seen","never saw","have never saw","am never seeing"],cue:"never",
   why:"never は have と過去分詞の間に置く。see の過去分詞は seen（saw は過去形）。"},
  {id:9,t:"exp",jp:"彼女はこの本を3回読んだことがある。",en:"She has read this book three times.",
   blank:"has read",o:["has read","read","is reading","has been reading"],cue:"three times",
   why:"three times（3回）は回数＝経験。read の過去分詞は read（つづりは同じで発音がレッド）。"},
  {id:10,t:"exp",jp:"前に彼に会ったことがある。",en:"I have met him before.",
   blank:"have met",o:["have met","met","have meet","was meeting"],cue:"before",
   why:"before（以前に）は経験の合図。meet の過去分詞は met。"},

  // ===== done: もう終わった（今もその状態） =====
  {id:11,t:"done",jp:"電車はすでに出発してしまった。",en:"The train has already left.",
   blank:"has already left",o:["has already left","already left","is already leaving","had already left"],cue:"already",
   why:"出発した結果、今ここに電車がない。already は has と過去分詞の間。had にすると過去のある時点より前の話になる。"},
  {id:12,t:"done",jp:"ちょうど仕事を終えたところだ。",en:"I have just finished my work.",
   blank:"have just finished",o:["have just finished","just finished","am just finishing","had just finished"],cue:"just",
   why:"just（ちょうど今）は完了の合図。終わった直後で今もその状態。"},
  {id:13,t:"done",jp:"まだそのメールを読んでいない。",en:"I have not read the email yet.",
   blank:"have not read",o:["have not read","did not read","am not reading","have not readed"],cue:"yet",
   why:"yet（まだ）は否定文で「まだ〜していない」。read の過去分詞は read（readed という形はない）。"},
  {id:14,t:"done",jp:"彼は鍵をなくしてしまった。",en:"He has lost his key.",
   blank:"has lost",o:["has lost","lost","is losing","has lose"],cue:"",
   why:"なくした結果、今も見つかっていない。lost だと過去の出来事の報告で、今どうなのかを言わない。"},
  {id:15,t:"done",jp:"もう終わりましたか？",en:"Have you finished it yet?",
   blank:"Have you finished",o:["Have you finished","Did you finish","Are you finishing","Have you finish"],cue:"yet",
   why:"疑問文の yet は「もう」。Did you finish だと「（あの時）終わらせたか」になる。"},

  // ===== past: いつを言うなら過去形 =====
  {id:16,t:"past",jp:"去年、京都に行った。",en:"I went to Kyoto last year.",
   blank:"went",o:["went","have been","have gone","was going"],cue:"last year",
   why:"last year（去年）という「いつ」があるので過去形。have been to は「いつ」と同じ文に入れられない。"},
  {id:17,t:"past",jp:"昨日、彼に会った。",en:"I saw him yesterday.",
   blank:"saw",o:["saw","have seen","have met","was seeing"],cue:"yesterday",
   why:"yesterday があるので過去形。「会ったことがある」なら have met だが、この文は日付を言っている。"},
  {id:18,t:"past",jp:"彼女は2時間前にそれを終わらせた。",en:"She finished it two hours ago.",
   blank:"finished",o:["finished","has finished","has been finishing","was finishing"],cue:"two hours ago",
   why:"〜ago（〜前）は過去の一点。for two hours（2時間ずっと）と混同しやすいので区別する。"},
  {id:19,t:"past",jp:"それはいつ買ったの？",en:"When did you buy it?",
   blank:"did you buy",o:["did you buy","have you bought","you have bought","are you buying"],cue:"When",
   why:"When（いつ）で聞く質問は必ず過去形。いつを聞いている以上、完了形は使えない。"},
  {id:20,t:"past",jp:"彼は2020年に日本に来た。",en:"He came to Japan in 2020.",
   blank:"came",o:["came","has come","has been coming","was coming"],cue:"in 2020",
   why:"in 2020 は年を指定している＝いつの話。since 2020（2020年から）なら完了形になる。"},

  // ===== now: 今この瞬間だけ =====
  {id:21,t:"now",jp:"私は彼を知っている。",en:"I know him.",
   blank:"know",o:["know","am knowing","have knowing","was knowing"],cue:"",
   why:"know は「知っている状態」で、動作ではないので ing にできない。日本語が「〜している」でも進行形にしない代表例。"},
  {id:22,t:"now",jp:"今、本を読んでいる。",en:"I am reading a book now.",
   blank:"am reading",o:["am reading","read","have read","have been reading"],cue:"now",
   why:"now（今）だけで期間の言葉がないので、目の前の動作。これが進行形の本来の使い方。"},
  {id:23,t:"now",jp:"彼女は新しい電話をほしがっている。",en:"She wants a new phone.",
   blank:"wants",o:["wants","is wanting","has wanted","is wanted"],cue:"",
   why:"want も状態なので ing にしない。know・like・have・need も同じ仲間。"},
  {id:24,t:"now",jp:"私には兄弟が2人いる。",en:"I have two brothers.",
   blank:"have",o:["have","am having","have been having","having"],cue:"",
   why:"have（持っている・いる）は状態。am having は「食べている最中」など別の意味になる。"},
  {id:25,t:"now",jp:"彼は今、外で待っている。",en:"He is waiting outside now.",
   blank:"is waiting",o:["is waiting","waits","has waited","has been waiting"],cue:"now",
   why:"now だけで期間がないので進行形。for an hour が付いたら has been waiting になる。"},

  // ===== keepdo: ずっとやり続けている =====
  {id:26,t:"keepdo",jp:"彼女は2時間ずっとテニスをし続けている。",en:"She has been playing tennis for two hours.",
   blank:"has been playing",o:["has been playing","is playing","has played","was playing"],cue:"for two hours",
   why:"for two hours（期間）＋ play（動きのある動作）なので have been + ing。is playing だと今の一瞬だけになる。"},
  {id:27,t:"keepdo",jp:"今朝から雨が降り続いている。",en:"It has been raining since this morning.",
   blank:"has been raining",o:["has been raining","is raining","has rained","was raining"],cue:"since this morning",
   why:"since this morning から今まで降り続いている。has rained だと「降った（もう止んだ）」に寄る。"},
  {id:28,t:"keepdo",jp:"1時間ずっとあなたを待っています。",en:"I have been waiting for you for an hour.",
   blank:"have been waiting",o:["have been waiting","am waiting","have waited","was waiting"],cue:"for an hour",
   why:"待ち続けて今もまだ待っている。for が2回出てくるが、前は「〜を」後ろは「〜間」で役割が違う。"},
  {id:29,t:"keepdo",jp:"彼は5年間英語を勉強し続けている。",en:"He has been studying English for five years.",
   blank:"has been studying",o:["has been studying","is studying","has studied","was studying"],cue:"for five years",
   why:"「し続けている」と動作の継続を言いたいので have been + ing。has studied でも通じるが続いている感じが弱い。"},
  {id:30,t:"keepdo",jp:"彼らは一日中それに取り組み続けている。",en:"They have been working on it all day.",
   blank:"have been working",o:["have been working","are working","have worked","were working"],cue:"all day",
   why:"all day（一日中）は期間。今もまだ終わっていないので have been + ing。"},

  // ===== before2: 過去のある時点より前 =====
  {id:31,t:"before2",jp:"駅に着いた時には、電車はすでに出発していた。",en:"When I got to the station, the train had already left.",
   blank:"had already left",o:["had already left","was already leaving","has already left","already left"],cue:"When I got",
   why:"着いた（過去）より前に出発している。どちらが先かを示すために先に起きた方を had にする。"},
  {id:32,t:"before2",jp:"日本に来る前、彼は中国語を5年間勉強していた。",en:"Before he came to Japan, he had studied Chinese for five years.",
   blank:"had studied",o:["had studied","has studied","was studying","studied"],cue:"Before he came",
   why:"来た（過去）より前の話なので had。has にすると基準が今になってしまい、Before he came と噛み合わない。"},
  {id:33,t:"before2",jp:"ここに来る前、雪を見たことがなかった。",en:"I had never seen snow before I came here.",
   blank:"had never seen",o:["had never seen","have never seen","never saw","was never seeing"],cue:"before I came",
   why:"「あの時点まで経験がなかった」＝経験の話を過去にずらした形。have を had にするだけ。"},
  {id:34,t:"before2",jp:"電話した時には、彼女は仕事を終えていた。",en:"She had finished her work when I called her.",
   blank:"had finished",o:["had finished","has finished","was finishing","finished"],cue:"when I called",
   why:"電話した（過去）時点で、すでに終わっていた。両方を過去形にすると順番が分からなくなる。"},
  {id:35,t:"before2",jp:"私たちが着いた時、映画はもう始まっていた。",en:"The movie had already started when we arrived.",
   blank:"had already started",o:["had already started","has already started","was already starting","already started"],cue:"when we arrived",
   why:"着いた時点より前に始まっている。was starting だと「始まりかけていた」で、もう始まっていた事実と合わない。"},

  // ===== regret: あの時こうすべきだった =====
  {id:36,t:"regret",jp:"君は医者に行くべきだった（のに行かなかった）。",en:"You should have gone to the doctor.",
   blank:"should have gone",o:["should have gone","should go","should went","should have go"],cue:"should",
   why:"should go は「これから行くべき」。should have + 過去分詞にすると「あの時すべきだったのにしなかった」になる。"},
  {id:37,t:"regret",jp:"彼は疲れていたに違いない。",en:"He must have been tired.",
   blank:"must have been",o:["must have been","must be","must was","must have be"],cue:"must",
   why:"must be は「今疲れているに違いない」。過去のことを推測するので must have been。助動詞の後ろは必ず have。"},
  {id:38,t:"regret",jp:"彼女がそんなことを言ったはずがない。",en:"She cannot have said such a thing.",
   blank:"cannot have said",o:["cannot have said","must not have said","cannot say","cannot have say"],cue:"cannot",
   why:"「〜したはずがない」は cannot have + 過去分詞。must not have said は「言わなかったに違いない」で意味がずれる。"},
  {id:39,t:"regret",jp:"もっと早く確認しておくべきだった。",en:"I should have checked it earlier.",
   blank:"should have checked",o:["should have checked","should check","should checked","should have check"],cue:"should",
   why:"仕事で使いやすい形。should have の後ろは必ず過去分詞で、should checked という形は存在しない。"},
  {id:40,t:"regret",jp:"彼らは電車に乗り遅れたのかもしれない。",en:"They may have missed the train.",
   blank:"may have missed",o:["may have missed","may miss","may missed","may have miss"],cue:"may",
   why:"may have + 過去分詞で「〜したのかもしれない」。may miss だと「これから乗り遅れるかも」。"},
];
