// 現在完了の次から高校まで（4ステージ・13の型・基本65文＋追加39文＝104文）
// lv を付けない文＝基本（型ごと5文）。lv:2 の文＝追加（型ごと3文）で、
// その型で1回でも間違えると解放され、以後その型は8文で回る。記録は localStorage の missT。
// 診断の起点は「現在完了」で、そこは kanryo.js が担当する。ここはその続き。
// 並べ方はカリキュラム順ではなく「同じ部品を使い回す順」にしてある。
//   ステージ1 うしろから飾る → ステージ2 つなぎを増やす → ステージ3 to と ing → ステージ4 事実でない話・文をくっつける
// 誤答には診断で出た癖（「〜している/していた」を全部 be + ing にする）を入れている。
// o[0] が必ず正解。表示時にシャッフルする。

const SSTAGES=[
  {id:"s1",name:"うしろから飾る",
   lead:"日本語は「立っている男性」と前から飾るが、英語は名詞のうしろに置く。ここが分かると関係代名詞まで一気に繋がる。"},
  {id:"s2",name:"つなぎを増やす",
   lead:"場所・時・理由でつなぐ形と、文の中に疑問文を入れる形。うしろの文に欠けている要素があるかどうかで使い分ける。"},
  {id:"s3",name:"to と ing",
   lead:"動詞を名詞のように使う2つの形。どちらを使うかで意味が変わる動詞がある。"},
  {id:"s4",name:"事実でない話・文をくっつける",
   lead:"実際にはそうでないことを言う形と、2つの文を1つにまとめる形。高校範囲の山場。"}
];

const STYPES=[
  // ===== ステージ1 =====
  {id:"ing-mod",s:"s1",name:"している方（うしろから飾る）",form:"名詞 + ing",cue:"文にもう動詞がある",
   core:"「向こうに立っている男性」は英語では「男性 → 立っている」の順。文の動詞は別にあるので、飾る側は ing だけを置く。",
   ng:"is standing（文の動詞が2つになる。飾るだけなら be は付けない）"},
  {id:"ed-mod",s:"s1",name:"された方（うしろから飾る）",form:"名詞 + 過去分詞",cue:"される側・されたもの",
   core:"「英語で書かれた手紙」は手紙が「書かれた」側なので過去分詞。ing にすると「書いている手紙」になってしまう。",
   ng:"was written（文の動詞が2つになる）/ writing（する側になってしまう）"},
  {id:"rel-who",s:"s1",name:"人や物を説明する（主語が抜ける位置）",form:"who / which / that / whose",cue:"うしろにすぐ動詞が来る",
   core:"飾る言葉が長くなって文の形になったもの。うしろの文で主語が抜けていれば who・which・that。うしろに名詞が続くなら whose。",
   ng:"人に which / 物に who / 所有なのに which"},
  {id:"rel-obj",s:"s1",name:"説明の中で目的語が抜ける",form:"名詞 + 主語 + 動詞（that は省略可）",cue:"うしろに主語と動詞が続く",
   core:"「私が読んだ本」は book が read の目的語。前に出ているので、read のうしろに it を置かない。ここが日本語からいちばんずれる。",
   ng:"I read it（目的語が二重になる）/ that I read it（同じ）"},

  // ===== ステージ2 =====
  {id:"rel-adv",s:"s2",name:"場所・時・理由でつなぐ",form:"where / when / why",cue:"うしろの文に欠けがない",
   core:"うしろの文が主語も目的語も揃っていて欠けがないときは、場所なら where、時なら when、理由なら why。",
   ng:"which（うしろの文に欠けがないと使えない）"},
  {id:"rel-prep",s:"s2",name:"前置詞を前に出す（かたい言い方）",form:"前置詞 + which",cue:"in / on / about / for",
   core:"where は「in which」と同じ意味。文書やかたい場面では前置詞を which の前に出す。that は前置詞の後ろに置けない。",
   ng:"in that（前置詞 + that は使えない）"},
  {id:"indirect",s:"s2",name:"文の中に疑問文を入れる",form:"疑問詞 + 主語 + 動詞",cue:"知っている・教えて・説明して",
   core:"疑問文が文の一部になると、語順がふつうの順に戻る。does he live ではなく he lives。",
   ng:"where does he live（疑問文の語順のまま）/ where is he living（進行形にする）"},

  // ===== ステージ3 =====
  {id:"it-to",s:"s3",name:"〜するのは…だ",form:"It is … (for 人) to do",cue:"difficult / important / easy",
   core:"主語が長くなるのを避けて It で始める。誰がするかを言うときは for 人。ただし人の性格を言う形容詞のときだけ of 人。",
   ng:"for me speaking（to が要る）/ of me to speak（difficult は for）"},
  {id:"want-to",s:"s3",name:"人に〜してもらう",form:"動詞 + 人 + to do",cue:"want / tell / ask",
   core:"want・tell・ask は「人 + to + 動詞」。ただし make・let・have のときだけ to が消える。",
   ng:"want that he comes（この形は使わない）/ make us to work（make に to は付かない）"},
  {id:"ing-to",s:"s3",name:"ing と to で意味が変わる",form:"stop / forget / remember / try",cue:"どちらも文として成立する",
   core:"ing は「もうやったこと・やっていたこと」、to は「これからやること」。stop singing は歌うのをやめる、stop to sing は歌うために立ち止まる。",
   ng:"意味を考えずにどちらかに決める"},

  // ===== ステージ4 =====
  {id:"if-now",s:"s4",name:"今そうではない話",form:"If + 過去形, 主語 + would + 動詞",cue:"If / I wish",
   core:"今は違う、という前提で言うときは、時間を1つ後ろにずらして過去形にする。be動詞は主語が I でも were。",
   ng:"If I have time, I will …（これは本当にあり得る話のとき）"},
  {id:"if-past",s:"s4",name:"あの時そうではなかった話",form:"If + had + 過去分詞, 主語 + would have + 過去分詞",cue:"earlier / then",
   core:"過去にそうしなかったことを言うときは、さらに1つ後ろにずらして had + 過去分詞。うしろの文は would / could have + 過去分詞。",
   ng:"If I knew earlier（過去の話なのに1段しかずらしていない）"},
  {id:"bunshi",s:"s4",name:"2つの文を1つにまとめる",form:"ing / 過去分詞 で文を始める",cue:"文頭にカンマまでのかたまり",
   core:"主語が同じ2つの文は、前の文の動詞を ing にして繋げられる。される側なら過去分詞で始める。打ち消しは not を前に置く。",
   ng:"I looking（主語を残したまま ing にする）/ Writing in English（される側なのに ing）"}
];

const SSENTS=[
  // ===== ing-mod: している方（うしろから飾る） =====
  {id:1,key:1,swap:["The woman sitting next to me is our client.","The people waiting outside are from the vendor."],t:"ing-mod",jp:"向こうに立っている男性は私の上司です。",en:"The man standing over there is my boss.",
   blank:"standing",o:["standing","is standing","stands","stood"],cue:"is my boss",
   why:"文の動詞は is。男性を「立っている」と飾るだけなので ing をそのまま置く。is standing にすると動詞が2つになる。"},
  {id:2,t:"ing-mod",jp:"会議に出ている人たちはみな部長です。",en:"The people attending the meeting are all managers.",
   blank:"attending",o:["attending","are attending","attend","attended"],cue:"are all managers",
   why:"文の動詞は are。「出ている」は人たちを飾るだけ。are attending にすると「今出席している最中だ」という別の文になる。"},
  {id:3,t:"ing-mod",jp:"隣に座っている女性が発表者です。",en:"The woman sitting next to me is the presenter.",
   blank:"sitting",o:["sitting","is sitting","sits","sat"],cue:"is the presenter",
   why:"文の動詞は is。女性を飾るだけなので ing。日本語の「座っている」に引かれて be を足さない。"},
  {id:4,t:"ing-mod",jp:"私に話しかけてきた男性は記者だった。",en:"The man speaking to me was a reporter.",
   blank:"speaking",o:["speaking","was speaking","spoke","spoken"],cue:"was a reporter",
   why:"文の動詞は was。過去の話でも、飾る側は ing のまま変わらない。"},
  {id:5,t:"ing-mod",jp:"あそこで待っているお客様が次の方です。",en:"The client waiting over there is next.",
   blank:"waiting",o:["waiting","is waiting","waits","waited"],cue:"is next",
   why:"文の動詞は is。「待っている」はお客様を飾るだけなので ing。"},

  // ===== ed-mod: された方（うしろから飾る） =====
  {id:6,t:"ed-mod",jp:"英語で書かれた手紙が届いた。",en:"A letter written in English arrived.",
   blank:"written",o:["written","writing","was written","wrote"],cue:"in English",
   why:"手紙は「書かれた」側なので過去分詞。文の動詞は arrived。writing にすると「書いている手紙」になる。"},
  {id:7,t:"ed-mod",jp:"昨日送られた資料を確認しました。",en:"I checked the documents sent yesterday.",
   blank:"sent",o:["sent","sending","were sent","send"],cue:"yesterday",
   why:"資料は「送られた」側なので過去分詞。文の動詞は checked なので were sent は要らない。"},
  {id:8,t:"ed-mod",jp:"中国で作られた部品を使っています。",en:"We use parts made in China.",
   blank:"made",o:["made","making","are made","make"],cue:"in China",
   why:"部品は「作られた」側なので過去分詞。making だと部品が何かを作っていることになる。"},
  {id:9,key:1,swap:["I will share the documents sent yesterday.","I will share the plan approved by the manager."],t:"ed-mod",jp:"会議で決まったことを共有します。",en:"I will share the points decided at the meeting.",
   blank:"decided",o:["decided","deciding","were decided","decide"],cue:"at the meeting",
   why:"決まった内容は「決められた」側なので過去分詞。日本語の「決まった」は受け身だと気づきにくい。"},
  {id:10,t:"ed-mod",jp:"田中さんに推薦された候補者に会った。",en:"I met the candidate recommended by Tanaka.",
   blank:"recommended",o:["recommended","recommending","was recommended","recommend"],cue:"by Tanaka",
   why:"候補者は「推薦された」側なので過去分詞。by が付いているのが され側の合図。"},

  // ===== rel-who: 主語が抜ける位置 =====
  {id:11,key:1,swap:["I am looking for someone who knows this system.","I am looking for someone who can join tomorrow."],t:"rel-who",jp:"英語を話せる人を探しています。",en:"I am looking for someone who can speak English.",
   blank:"who",o:["who","which","whose","whom"],cue:"someone",
   why:"探しているのは人なので who。うしろに can speak が続く＝説明の中で主語が抜けている位置。"},
  {id:12,t:"rel-who",jp:"駅の近くにあるレストランに行った。",en:"I went to a restaurant which is near the station.",
   blank:"which",o:["which","who","whose","where"],cue:"a restaurant",
   why:"説明されるのは物（restaurant）なので which。うしろに is が続く＝主語の位置。"},
  {id:13,t:"rel-who",jp:"赤い屋根の家が私の家です。",en:"The house whose roof is red is mine.",
   blank:"whose",o:["whose","which","who","that"],cue:"roof",
   why:"「家の屋根」は所有の関係なので whose。whose のうしろには名詞（roof）が続くのが見分け方。"},
  {id:14,t:"rel-who",jp:"3時に始まる会議に出ます。",en:"I will attend the meeting that starts at three.",
   blank:"that",o:["that","who","whose","what"],cue:"the meeting",
   why:"that は人にも物にも使える。うしろに starts が続く＝主語の位置。what はここでは使えない。"},
  {id:15,t:"rel-who",jp:"うちで働いているエンジニアは5人います。",en:"We have five engineers who work here.",
   blank:"who",o:["who","which","whose","whom"],cue:"engineers",
   why:"人が複数でも who は変わらない。うしろに work が続く＝主語の位置。"},

  // ===== rel-obj: 目的語が抜ける =====
  {id:16,t:"rel-obj",jp:"私が昨日読んだ本はおもしろかった。",en:"The book I read yesterday was interesting.",
   blank:"I read",o:["I read","I read it","that I read it","I was reading"],cue:"yesterday",
   why:"読んだ対象（book）が前に出ているので、read のうしろに it を置かない。that は入れても省略してもよい。"},
  {id:17,t:"rel-obj",jp:"彼が話していた会社はうちの取引先だ。",en:"The company he was talking about is our client.",
   blank:"he was talking about",o:["he was talking about","he was talking","he was talking about it","which he was talking"],cue:"our client",
   why:"talk about の about は残す。about の目的語（company）が前に出ているので it は置かない。"},
  {id:18,t:"rel-obj",jp:"私が先週会った人から連絡が来た。",en:"The person I met last week contacted me.",
   blank:"I met",o:["I met","I met him","that I met him","I was meeting"],cue:"last week",
   why:"会った相手（person）が前に出ているので him を置かない。that を足すなら him は消す。"},
  {id:19,t:"rel-obj",jp:"部長が選んだ候補はこの2つです。",en:"The options the manager chose are these two.",
   blank:"the manager chose",o:["the manager chose","the manager chose them","which the manager chose them","the manager was choosing"],cue:"these two",
   why:"選んだ対象（options）が前に出ているので them を置かない。that や which は省略できる。"},
  {id:20,key:1,swap:["I cannot open the link you shared.","I cannot find the document he uploaded."],t:"rel-obj",jp:"あなたが送ってくれたファイルが開けません。",en:"I cannot open the file you sent.",
   blank:"you sent",o:["you sent","you sent it","that you sent it","you were sending"],cue:"cannot open",
   why:"送ったもの（file）が前に出ているので it を置かない。この形がいちばん短く自然。"},


  // ===== rel-adv: 場所・時・理由でつなぐ =====
  {id:21,key:1,swap:["This is the room where we meet every Monday.","This is the folder where I keep the records."],t:"rel-adv",jp:"これが私が働いている会社です。",en:"This is the company where I work.",
   blank:"where",o:["where","which","who","what"],cue:"I work",
   why:"うしろの I work は主語も動詞も揃っていて欠けがない。だから場所を指す where。which は主語か目的語が抜けていないと使えない。"},
  {id:22,t:"rel-adv",jp:"彼が生まれた年を覚えていますか。",en:"Do you remember the year when he was born?",
   blank:"when",o:["when","where","which","what"],cue:"the year",
   why:"説明されるのが時（year）で、うしろの文に欠けがないので when。"},
  {id:23,t:"rel-adv",jp:"彼が辞めた理由は分からない。",en:"I do not know the reason why he quit.",
   blank:"why",o:["why","how","when","which"],cue:"the reason",
   why:"説明されるのが理由（reason）なので why。reason why はセットで覚えてよい。"},
  {id:24,t:"rel-adv",jp:"ここが事故が起きた場所です。",en:"This is the place where the accident happened.",
   blank:"where",o:["where","which","when","that"],cue:"the accident",
   why:"place を説明していて、うしろの文に欠けがないので where。"},
  {id:25,t:"rel-adv",jp:"締め切りに間に合った日を覚えている。",en:"I remember the day when we met the deadline.",
   blank:"when",o:["when","where","why","which"],cue:"the deadline",
   why:"day を説明していて、うしろの we met the deadline に欠けがないので when。"},

  // ===== rel-prep: 前置詞 + which =====
  {id:26,key:1,swap:["This is the process in which we check the data.","話すときは where で足りる。in which は文書やかたい場面だけ。"],t:"rel-prep",jp:"これが私が働いている会社です（かたい言い方）。",en:"This is the company in which I work.",
   blank:"in which",o:["in which","which","in that","where in"],cue:"I work",
   why:"where と同じ意味を前置詞で書いた形。work in the company の in を which の前に出している。in that は使えない。"},
  {id:27,t:"rel-prep",jp:"これが私が頼っている方法です。",en:"This is the method on which I rely.",
   blank:"on which",o:["on which","which","on that","which on"],cue:"I rely",
   why:"rely on の on を前に出す。どの前置詞になるかは、もとの動詞が取る前置詞で決まる。"},
  {id:28,t:"rel-prep",jp:"彼が話していた問題は解決した。",en:"The problem about which he talked has been solved.",
   blank:"about which",o:["about which","which about","that about","about that"],cue:"he talked",
   why:"talk about の about を前に出す。about which の順で、逆にはしない。"},
  {id:29,t:"rel-prep",jp:"会議を開いた部屋は狭かった。",en:"The room in which we held the meeting was small.",
   blank:"in which",o:["in which","which","in that","where in"],cue:"the meeting",
   why:"hold the meeting in the room の in を前に出した形。where に置き換えても同じ意味になる。"},
  {id:30,t:"rel-prep",jp:"彼が来た理由は分からない。",en:"I do not know the reason for which he came.",
   blank:"for which",o:["for which","which for","that for","for that"],cue:"he came",
   why:"why をかたく書くと for which。reason for 〜 の for を前に出している。"},

  // ===== indirect: 文の中に疑問文を入れる =====
  {id:31,t:"indirect",jp:"彼がどこに住んでいるか知っていますか。",en:"Do you know where he lives?",
   blank:"where he lives",o:["where he lives","where does he live","where he live","where is he living"],cue:"Do you know",
   why:"疑問文が文の一部になると、does he live という語順が he lives に戻る。「住んでいる」に引かれて is living にしない。"},
  {id:32,t:"indirect",jp:"彼が何を言ったか教えてください。",en:"Please tell me what he said.",
   blank:"what he said",o:["what he said","what did he say","what he say","what was he saying"],cue:"tell me",
   why:"did he say ではなく he said。文の中に入ると過去形はそのまま動詞に残る。"},
  {id:33,t:"indirect",jp:"なぜ遅れたのか説明してもらえますか。",en:"Can you explain why you were late?",
   blank:"why you were late",o:["why you were late","why were you late","why you late","why are you late"],cue:"explain",
   why:"were you late という語順が you were late に戻る。be動詞も同じ扱い。"},
  {id:34,key:1,swap:["I do not know when it will start.","I do not know who will join."],t:"indirect",jp:"いつ終わるか分かりません。",en:"I do not know when it will finish.",
   blank:"when it will finish",o:["when it will finish","when will it finish","when it finishes","when is it finishing"],cue:"do not know",
   why:"ここは「いつ終わるか」という中身のかたまりなので will を使える。「終わったら連絡する」のような条件の when なら現在形にする（別のルール）。"},
  {id:35,t:"indirect",jp:"この件を誰が決めたか知りたい。",en:"I want to know who decided this.",
   blank:"who decided this",o:["who decided this","who did decide this","who this decided","who was deciding this"],cue:"want to know",
   why:"who が主語のときは語順がもともと変わらない。did を足さないのがここの落とし穴。"},

  // ===== it-to: 〜するのは…だ =====
  {id:36,t:"it-to",jp:"英語で話すのは私には難しい。",en:"It is difficult for me to speak English.",
   blank:"for me to speak",o:["for me to speak","for me speaking","of me to speak","for I to speak"],cue:"difficult",
   why:"It で始めて、誰がするかは for 人、何をするかは to + 動詞。difficult のときは of ではなく for。"},
  {id:37,key:1,swap:["It is important to check it first.","It is important to tell the client early."],t:"it-to",jp:"締め切りを守ることが大切だ。",en:"It is important to meet the deadline.",
   blank:"to meet",o:["to meet","meeting","meet","for meeting"],cue:"important",
   why:"誰がするかを言わないときは for 人を省いて to + 動詞だけ。It is important meeting とは言わない。"},
  {id:38,t:"it-to",jp:"彼が一人でやるのは無理だった。",en:"It was impossible for him to do it alone.",
   blank:"for him to do",o:["for him to do","for him doing","of him to do","for he to do"],cue:"alone",
   why:"for のうしろは him（he ではない）。impossible は難しさを言う形容詞なので for。"},
  {id:39,t:"it-to",jp:"彼女がそう言うのは親切だった。",en:"It was kind of her to say so.",
   blank:"of her to say",o:["of her to say","for her to say","of her saying","for she to say"],cue:"kind",
   why:"kind・careless のように人の性格を言う形容詞のときだけ of 人。difficult・easy のときは for 人。"},
  {id:40,t:"it-to",jp:"毎日記録するのは簡単ではない。",en:"It is not easy to record it every day.",
   blank:"to record",o:["to record","recording","record","for recording"],cue:"every day",
   why:"easy は for 人を付けなければ to + 動詞だけ。not は is のうしろに置く。"},

  // ===== want-to: 人に〜してもらう =====
  {id:41,key:1,swap:["My manager asked me to join the meeting.","My manager wants me to explain the plan."],t:"want-to",jp:"部長は私に報告書を書くよう言った。",en:"My manager told me to write the report.",
   blank:"me to write",o:["me to write","me write","to me to write","me writing"],cue:"the report",
   why:"tell は「人 + to + 動詞」。tell のうしろに to は付けない（to me としない）。"},
  {id:42,t:"want-to",jp:"彼に来てほしい。",en:"I want him to come.",
   blank:"him to come",o:["him to come","that he comes","him come","him coming"],cue:"I want",
   why:"want は「人 + to + 動詞」。I want that he comes という形は英語では使わない。"},
  {id:43,t:"want-to",jp:"彼女に手伝ってくれるよう頼んだ。",en:"I asked her to help me.",
   blank:"her to help",o:["her to help","her help","that she helps","her helping"],cue:"I asked",
   why:"ask も「人 + to + 動詞」。頼む相手は her（she ではない）。"},
  {id:44,t:"want-to",jp:"上司は私たちに残業させなかった。",en:"My boss did not make us work late.",
   blank:"us work",o:["us work","us to work","us working","that we work"],cue:"late",
   why:"make・let・have のときだけ to が消える。tell・ask・want との違いはここ。"},
  {id:45,t:"want-to",jp:"彼に決めてもらうことにした。",en:"I decided to let him decide.",
   blank:"let him decide",o:["let him decide","let him to decide","let him deciding","let he decide"],cue:"I decided",
   why:"let も to が付かない仲間。うしろは him（he ではない）＋動詞そのまま。"},

  // ===== ing-to: ing と to で意味が変わる =====
  {id:46,t:"ing-to",jp:"歌うのをやめた。",en:"I stopped singing.",
   blank:"singing",o:["singing","to sing","sing","sung"],cue:"stopped",
   why:"stop + ing は「していたことをやめる」。stop to sing にすると「歌うために立ち止まる」という別の意味になる。"},
  {id:47,key:1,swap:["I forgot to send the file.","I remembered to check the log."],t:"ing-to",jp:"電話するのを忘れた。",en:"I forgot to call him.",
   blank:"to call",o:["to call","calling","call","called"],cue:"forgot",
   why:"forget + to は「するのを忘れた（まだしていない）」。forget + ing は「したことを忘れた」。ここはまだ電話していない。"},
  {id:48,t:"ing-to",jp:"鍵をかけたのを覚えている。",en:"I remember locking the door.",
   blank:"locking",o:["locking","to lock","lock","locked"],cue:"remember",
   why:"remember + ing は「したことを覚えている」。もうかけてある話なので ing。"},
  {id:49,t:"ing-to",jp:"報告するのを覚えておいて。",en:"Please remember to report it.",
   blank:"to report",o:["to report","reporting","report","reported"],cue:"Please remember",
   why:"remember + to は「これからするのを忘れないで」。48と同じ動詞でも、これからの話なので to。"},
  {id:50,t:"ing-to",jp:"彼と話そうとしたが通じなかった。",en:"I tried to talk to him but he did not understand.",
   blank:"to talk",o:["to talk","talking","talk","talked"],cue:"tried",
   why:"try + to は「しようと試みる（できたとは限らない）」。try + ing は「試しにやってみる」。通じなかったので to。"},

  // ===== if-now: 今そうではない話 =====
  {id:51,key:1,swap:["If I were you, I would ask him first.","If we had more people, we would finish today."],t:"if-now",jp:"時間があれば手伝うのに。",en:"If I had time, I would help you.",
   blank:"had",o:["had","have","will have","would have"],cue:"I would help",
   why:"今は時間がないという前提なので、時間を1つ後ろにずらして過去形にする。うしろの文は would + 動詞。"},
  {id:52,t:"if-now",jp:"私が君なら断る。",en:"If I were you, I would refuse.",
   blank:"were",o:["were","am","was","would be"],cue:"I would refuse",
   why:"事実と違う話をするときの be動詞は were。主語が I でも was にしない。"},
  {id:53,t:"if-now",jp:"もっと英語ができれば海外で働く。",en:"If I could speak English better, I would work abroad.",
   blank:"could speak",o:["could speak","can speak","will speak","would speak"],cue:"abroad",
   why:"can も1つ後ろにずらして could。うしろの文は would + 動詞のまま。"},
  {id:54,t:"if-now",jp:"彼が来たら話が進むのに。",en:"If he came, things would move forward.",
   blank:"came",o:["came","comes","will come","would come"],cue:"move forward",
   why:"実際には来ないと思っているので過去形。If he comes だと本当に来る可能性がある話になる。"},
  {id:55,t:"if-now",jp:"お金があればいいのに。",en:"I wish I had more money.",
   blank:"had",o:["had","have","will have","would have"],cue:"I wish",
   why:"I wish のうしろも事実と違う話なので過去形。I wish I have とは言わない。"},

  // ===== if-past: あの時そうではなかった話 =====
  {id:56,key:1,swap:["If we had checked it, we could have prevented it.","If I had asked earlier, I could have fixed it."],t:"if-past",jp:"もっと早く知っていれば止められたのに。",en:"If I had known earlier, I could have stopped it.",
   blank:"had known",o:["had known","knew","have known","would know"],cue:"earlier",
   why:"過去にそうしなかった話なので、さらに1つずらして had + 過去分詞。うしろの文は could have + 過去分詞。"},
  {id:57,t:"if-past",jp:"彼が来ていれば結論が出ていた。",en:"If he had come, we would have decided.",
   blank:"had come",o:["had come","came","has come","would come"],cue:"we would have decided",
   why:"うしろが would have decided なので、if のほうも過去のさらに前＝had + 過去分詞にそろえる。"},
  {id:58,t:"if-past",jp:"確認していれば防げた。",en:"If we had checked it, we could have prevented it.",
   blank:"had checked",o:["had checked","checked","have checked","would check"],cue:"prevented",
   why:"確認しなかったという過去の事実に反する話。has checked では今の話になってしまう。"},
  {id:59,t:"if-past",jp:"あの時言っておけばよかった。",en:"I wish I had said it then.",
   blank:"had said",o:["had said","said","have said","would say"],cue:"I wish",
   why:"I wish で過去のことを悔やむときは had + 過去分詞。今のことなら過去形（55と対で覚える）。"},
  {id:60,t:"if-past",jp:"もっと準備すべきだった。",en:"I should have prepared more.",
   blank:"should have prepared",o:["should have prepared","should prepare","should be prepared","should have prepare"],cue:"more",
   why:"「あの時こうすべきだった」は 助動詞 + have + 過去分詞。should prepare だと今の話になる。"},

  // ===== bunshi: 2つの文を1つにまとめる =====
  {id:61,key:1,swap:["Checking the log, I found the cause.","Reading the report, I noticed the error."],t:"bunshi",jp:"資料を見ながら説明した。",en:"Looking at the material, I explained it.",
   blank:"Looking",o:["Looking","Looked","I looking","To look"],cue:"I explained",
   why:"主語が同じ2つの文をまとめるとき、前の文の動詞を ing にする。主語（I）は残さない。"},
  {id:62,t:"bunshi",jp:"英語で書かれているので読めなかった。",en:"Written in English, it was hard for me to read.",
   blank:"Written",o:["Written","Writing","It written","To write"],cue:"in English",
   why:"それは「書かれた」側なので過去分詞から始める。Writing にすると「書きながら」になる。"},
  {id:63,t:"bunshi",jp:"電車を降りて、彼に電話した。",en:"Getting off the train, I called him.",
   blank:"Getting",o:["Getting","Got","I getting","To get"],cue:"I called him",
   why:"降りたのも電話したのも I。前の動作を ing にして繋げる。and で繋いでも意味は同じ。"},
  {id:64,t:"bunshi",jp:"遅れたので謝った。",en:"Being late, I apologized.",
   blank:"Being",o:["Being","Be","I being","To be"],cue:"I apologized",
   why:"be動詞も ing にできる。Being late で「遅れたので」という理由になる。"},
  {id:65,t:"bunshi",jp:"何をすべきか分からず、彼は黙っていた。",en:"Not knowing what to do, he kept silent.",
   blank:"Not knowing",o:["Not knowing","Knowing not","Not know","Do not knowing"],cue:"he kept silent",
   why:"打ち消しは ing の前に not を置く。Knowing not の順にはしない。"},

  // ===== ここから lv:2 ＝ 追加の文。その型で間違えると解放される =====
  {id:101,t:"ing-mod",lv:2,jp:"受付に立っている人に聞いてください。",en:"Please ask the person standing at the reception.",
   blank:"standing",o:["standing","is standing","stands","stood"],cue:"at the reception",
   why:"文の動詞は ask。人を飾るだけなので ing をそのまま置く。"},
  {id:102,t:"ing-mod",lv:2,jp:"電話で話している男性が課長です。",en:"The man talking on the phone is the section chief.",
   blank:"talking",o:["talking","is talking","talks","talked"],cue:"is the section chief",
   why:"文の動詞は is。男性を飾るだけなので ing。is talking にすると動詞が2つになる。"},
  {id:103,t:"ing-mod",lv:2,jp:"走っている子どもたちを見た。",en:"I saw the children running.",
   blank:"running",o:["running","are running","run","ran"],cue:"I saw",
   why:"文の動詞は saw。子どもたちを飾るだけなので ing。"},

  {id:104,t:"ed-mod",lv:2,jp:"日本で売られている車は小さい。",en:"Cars sold in Japan are small.",
   blank:"sold",o:["sold","selling","are sold","sell"],cue:"in Japan",
   why:"車は「売られる」側なので過去分詞。文の動詞は are small のほう。"},
  {id:105,t:"ed-mod",lv:2,jp:"部長に承認された案で進めます。",en:"We will proceed with the plan approved by the manager.",
   blank:"approved",o:["approved","approving","was approved","approve"],cue:"by the manager",
   why:"案は「承認された」側なので過去分詞。by が付いているのが され側の合図。"},
  {id:106,t:"ed-mod",lv:2,jp:"先週修理された機械がまた止まった。",en:"The machine repaired last week stopped again.",
   blank:"repaired",o:["repaired","repairing","was repaired","repair"],cue:"last week",
   why:"機械は「修理された」側なので過去分詞。文の動詞は stopped。"},

  {id:107,t:"rel-who",lv:2,jp:"この会社を作った人に会った。",en:"I met the person who founded this company.",
   blank:"who",o:["who","which","whose","what"],cue:"the person",
   why:"説明されるのは人なので who。うしろに founded が続く＝主語の位置。"},
  {id:108,t:"rel-who",lv:2,jp:"屋上にある機械が止まった。",en:"The machine which is on the roof stopped.",
   blank:"which",o:["which","who","whose","where"],cue:"the roof",
   why:"説明されるのは物なので which。うしろに is が続く＝主語の位置。"},
  {id:109,t:"rel-who",lv:2,jp:"名前を忘れた同僚に会った。",en:"I met a colleague whose name I forgot.",
   blank:"whose",o:["whose","which","who","that"],cue:"name",
   why:"「同僚の名前」は所有の関係なので whose。whose のうしろに名詞（name）が続く。"},

  {id:110,t:"rel-obj",lv:2,jp:"彼が推薦した本を買った。",en:"I bought the book he recommended.",
   blank:"he recommended",o:["he recommended","he recommended it","that he recommended it","he was recommending"],cue:"I bought",
   why:"推薦した対象（book）が前に出ているので it を置かない。that は入れても省略してもよい。"},
  {id:111,t:"rel-obj",lv:2,jp:"私が使っているパソコンは古い。",en:"The computer I use is old.",
   blank:"I use",o:["I use","I use it","that I use it","I am using"],cue:"is old",
   why:"使っている対象（computer）が前に出ているので it を置かない。「使っている」に引かれて am using にしない。"},
  {id:112,t:"rel-obj",lv:2,jp:"部長が言ったことを覚えている。",en:"I remember what the manager said.",
   blank:"what the manager said",o:["what the manager said","that the manager said","what the manager said it","which the manager said"],cue:"I remember",
   why:"「〜のこと」は what でまとめる。what が said の目的語を兼ねているので it は置かない。"},

  {id:113,t:"rel-adv",lv:2,jp:"私が生まれた町は小さい。",en:"The town where I was born is small.",
   blank:"where",o:["where","which","when","that"],cue:"I was born",
   why:"うしろの I was born に欠けがないので where。which は主語か目的語が抜けていないと使えない。"},
  {id:114,t:"rel-adv",lv:2,jp:"彼が辞めた日を忘れない。",en:"I will never forget the day when he quit.",
   blank:"when",o:["when","where","why","which"],cue:"the day",
   why:"説明されるのが時（day）で、うしろの文に欠けがないので when。"},
  {id:115,t:"rel-adv",lv:2,jp:"彼が怒った理由が分かった。",en:"I understood the reason why he got angry.",
   blank:"why",o:["why","how","when","where"],cue:"the reason",
   why:"説明されるのが理由（reason）なので why。"},

  {id:116,t:"rel-prep",lv:2,jp:"私が座っていた椅子が壊れた。",en:"The chair on which I was sitting broke.",
   blank:"on which",o:["on which","which","on that","which on"],cue:"I was sitting",
   why:"sit on the chair の on を which の前に出した形。on that とは言えない。"},
  {id:117,t:"rel-prep",lv:2,jp:"彼が働いている部署は忙しい。",en:"The department in which he works is busy.",
   blank:"in which",o:["in which","which","in that","where in"],cue:"he works",
   why:"work in the department の in を前に出す。where に置き換えても同じ意味。"},
  {id:118,t:"rel-prep",lv:2,jp:"私たちが話した話題は難しかった。",en:"The topic about which we talked was difficult.",
   blank:"about which",o:["about which","which about","that about","about that"],cue:"we talked",
   why:"talk about の about を前に出す。about which の順で、逆にはしない。"},

  {id:119,t:"indirect",lv:2,jp:"彼が誰か知っていますか。",en:"Do you know who he is?",
   blank:"who he is",o:["who he is","who is he","who he","who is he being"],cue:"Do you know",
   why:"文の中に入ると who is he の語順が who he is に戻る。"},
  {id:120,t:"indirect",lv:2,jp:"どこで買ったか教えて。",en:"Tell me where you bought it.",
   blank:"where you bought",o:["where you bought","where did you buy","where you buy","where were you buying"],cue:"Tell me",
   why:"did you buy ではなく you bought。過去形はそのまま動詞に残る。"},
  {id:121,t:"indirect",lv:2,jp:"何時に来るか分からない。",en:"I do not know what time he will come.",
   blank:"what time he will come",o:["what time he will come","what time will he come","what time he comes","what time is he coming"],cue:"do not know",
   why:"「何時に来るか」という中身のかたまりなので will を使える。語順は he will come に戻る。"},

  {id:122,t:"it-to",lv:2,jp:"時間通りに来ることが重要だ。",en:"It is important to come on time.",
   blank:"to come",o:["to come","coming","come","for coming"],cue:"on time",
   why:"誰がするかを言わないときは to + 動詞だけ。It is important coming とは言わない。"},
  {id:123,t:"it-to",lv:2,jp:"彼女がそれを一人で終えるのは大変だった。",en:"It was hard for her to finish it alone.",
   blank:"for her to finish",o:["for her to finish","for her finishing","of her to finish","for she to finish"],cue:"alone",
   why:"hard は難しさを言う形容詞なので for 人。for のうしろは her（she ではない）。"},
  {id:124,t:"it-to",lv:2,jp:"そう言ってくれるとはやさしい。",en:"It is nice of you to say that.",
   blank:"of you to say",o:["of you to say","for you to say","of you saying","for your to say"],cue:"nice",
   why:"nice は人の性格を言う形容詞なので of 人。difficult・hard のときは for 人。"},

  {id:125,t:"want-to",lv:2,jp:"彼に手伝ってほしい。",en:"I want him to help me.",
   blank:"him to help",o:["him to help","him help","that he helps","him helping"],cue:"I want",
   why:"want は「人 + to + 動詞」。I want that he helps という形は使わない。"},
  {id:126,t:"want-to",lv:2,jp:"上司は私に残るように頼んだ。",en:"My boss asked me to stay.",
   blank:"me to stay",o:["me to stay","me stay","to me to stay","me staying"],cue:"My boss asked",
   why:"ask は「人 + to + 動詞」。ask のうしろに to は付けない。"},
  {id:127,t:"want-to",lv:2,jp:"彼に自由にやらせた。",en:"I let him do it freely.",
   blank:"let him do",o:["let him do","let him to do","let him doing","let he do"],cue:"freely",
   why:"let は to が付かない仲間（make・have も同じ）。うしろは him ＋ 動詞そのまま。"},

  {id:128,t:"ing-to",lv:2,jp:"たばこをやめた。",en:"I stopped smoking.",
   blank:"smoking",o:["smoking","to smoke","smoke","smoked"],cue:"stopped",
   why:"stop + ing は「していたことをやめる」。stop to smoke だと「吸うために立ち止まる」になる。"},
  {id:129,t:"ing-to",lv:2,jp:"送るのを忘れないで。",en:"Do not forget to send it.",
   blank:"to send",o:["to send","sending","send","sent"],cue:"Do not forget",
   why:"forget + to は「これからするのを忘れないで」。まだ送っていないので to。"},
  {id:130,t:"ing-to",lv:2,jp:"彼に会ったのを覚えている。",en:"I remember meeting him.",
   blank:"meeting",o:["meeting","to meet","meet","met"],cue:"I remember",
   why:"remember + ing は「したことを覚えている」。もう会っている話なので ing。"},

  {id:131,t:"if-now",lv:2,jp:"車があれば行くのに。",en:"If I had a car, I would go.",
   blank:"had",o:["had","have","will have","would have"],cue:"I would go",
   why:"今は車がないという前提なので過去形。If I have a car, I will go なら本当に持てる話になる。"},
  {id:132,t:"if-now",lv:2,jp:"彼が上司なら違うだろう。",en:"If he were the manager, it would be different.",
   blank:"were",o:["were","is","was","would be"],cue:"it would be different",
   why:"事実と違う話なので be動詞は were。うしろの文は would + 動詞。"},
  {id:133,t:"if-now",lv:2,jp:"英語が読めれば楽なのに。",en:"I wish I could read English.",
   blank:"could read",o:["could read","can read","will read","would read"],cue:"I wish",
   why:"I wish のうしろは事実と違う話なので can を could にずらす。"},

  {id:134,t:"if-past",lv:2,jp:"聞いていれば分かったのに。",en:"If I had asked, I would have known.",
   blank:"had asked",o:["had asked","asked","have asked","would ask"],cue:"I would have known",
   why:"うしろが would have known なので、if のほうも had + 過去分詞にそろえる。"},
  {id:135,t:"if-past",lv:2,jp:"遅れなければ間に合った。",en:"If we had not been late, we could have made it.",
   blank:"had not been",o:["had not been","were not","have not been","would not be"],cue:"made it",
   why:"過去の事実に反する話なので had + 過去分詞。打ち消しは had のうしろに not。"},
  {id:136,t:"if-past",lv:2,jp:"もっと早く言えばよかった。",en:"I wish I had told you earlier.",
   blank:"had told",o:["had told","told","have told","would tell"],cue:"earlier",
   why:"I wish で過去を悔やむときは had + 過去分詞。今のことなら過去形にする。"},

  {id:137,t:"bunshi",lv:2,jp:"資料を読みながらメモを取った。",en:"Reading the material, I took notes.",
   blank:"Reading",o:["Reading","Read","I reading","To read"],cue:"I took notes",
   why:"読んだのもメモを取ったのも I。前の動作を ing にして繋げる。主語は残さない。"},
  {id:138,t:"bunshi",lv:2,jp:"時間がなかったので、彼は説明を省いた。",en:"Having no time, he skipped the explanation.",
   blank:"Having",o:["Having","Have","He having","To have"],cue:"he skipped",
   why:"have も ing にできる。Having no time で「時間がなかったので」という理由になる。"},
  {id:139,t:"bunshi",lv:2,jp:"理由が分からず、私は聞き返した。",en:"Not understanding the reason, I asked again.",
   blank:"Not understanding",o:["Not understanding","Understanding not","Not understand","Do not understanding"],cue:"I asked again",
   why:"打ち消しは ing の前に not を置く。Understanding not の順にはしない。"}
];
