// 英単語amida用データ。中1→高校のレベル層×代表サンプルで「どの帯から崩れるか」を診断する
// 単語は無限にあるが頻度順で層になっているので、各レベルの代表語で診断が成立する
// w=単語 jp=意味 hook=覚えるフック ex/exjp=例文 exw=例文中の語形（変化形の時だけ） deck=レベルid
// kind:"level" ＝ 頻度順のレベル。これだけが「崩れの起点」の診断に使われる。
// kind:"topic" ＝ 分野別。レベルではないので診断の判定には混ぜない（混ぜると起点がずれる）。
const WORD_DECKS=[
  {id:"m1",kind:"level",name:"中1レベル",desc:"毎日の動作の基本動詞"},
  {id:"m2",kind:"level",name:"中2レベル",desc:"やりとり・移動・気持ち"},
  {id:"m3",kind:"level",name:"中3レベル",desc:"経験・社会・少し抽象"},
  {id:"h1",kind:"level",name:"高校基礎レベル",desc:"提供する・要求する・利用できる"},
  {id:"h2",kind:"level",name:"高校標準レベル",desc:"評価する・維持する・有意な"},
  {id:"aws", kind:"topic",name:"AWS・クラウド",  desc:"配置する・冗長性・遅延・上限枠"},
  {id:"biz", kind:"topic",name:"ビジネス検討",  desc:"実現可能性・前提・成果物・得失"},
  {id:"econ",kind:"topic",name:"経済ニュース",  desc:"物価・利回り・関税・利益率"},
  {id:"art", kind:"topic",name:"アートの表現",  desc:"構図・質感・彩度・呼び起こす"},
  {id:"car", kind:"topic",name:"車・運転",      desc:"操舵・排気量・空力・操縦性"},
  // kind:"collocation" ＝ 単語ではなく「組み合わせ」を覚える。誤答肢は alt で指定する
  {id:"col-vn",  kind:"collocation",name:"動詞＋名詞の組み合わせ",  desc:"make a decision / take measures / place an order"},
  {id:"col-prep",kind:"collocation",name:"動詞＋前置詞の組み合わせ",desc:"depend on / comply with / discuss（aboutは不要）"},
];
const WORDS=[
// ===== 中1レベル =====
{w:"drink",jp:"飲む",hook:"ドリンク＝飲み物。「飲み物する」→飲む",ex:"I drink coffee every morning.",exjp:"毎朝コーヒーを飲む。",deck:"m1"},
{w:"live",jp:"住む",hook:"ライブ配信のlive＝「生の・生きている」。生きる場所→住む",ex:"She lives in Tokyo.",exjp:"彼女は東京に住んでいる。",deck:"m1"},
{w:"know",jp:"知っている",hook:"ノウハウ（know-how）＝やり方を知っていること",ex:"I know him.",exjp:"私は彼を知っている。",deck:"m1"},
{w:"run",jp:"走る",hook:"ランニング",ex:"She is running now.",exjp:"彼女は今走っている。",deck:"m1"},
{w:"swim",jp:"泳ぐ",hook:"スイミングスクール",ex:"She can swim fast.",exjp:"彼女は速く泳げる。",deck:"m1"},
{w:"open",jp:"開ける",hook:"オープン。開店＝店を開ける",ex:"Open the window.",exjp:"窓を開けなさい。",deck:"m1"},
{w:"study",jp:"勉強する",hook:"スタディサプリ",ex:"He didn't study last night.",exjp:"彼は昨夜勉強しなかった。",deck:"m1"},
{w:"work",jp:"働く",hook:"ワークライフバランス＝仕事と生活",ex:"You don't have to work today.",exjp:"今日は働かなくてもいい。",deck:"m1"},
{w:"buy",jp:"買う",hook:"バイヤー＝buy+er＝買う人",ex:"He went to the store to buy a book.",exjp:"本を買うために店へ行った。",deck:"m1"},
{w:"sing",jp:"歌う",hook:"シンガー＝sing+er＝歌う人",ex:"He stopped singing.",exjp:"彼は歌うのをやめた。",deck:"m1"},
{w:"see",jp:"見える・会う",hook:"シースルー＝透けて見える。see you＝また会おう",ex:"I'm looking forward to seeing her.",exjp:"彼女に会うのが楽しみだ。",deck:"m1"},
{w:"cook",jp:"料理する",hook:"クッキング",ex:"My mother was cooking.",exjp:"母は料理をしていた。",deck:"m1"},
{w:"watch",jp:"（動くものを）じっと見る",hook:"腕時計のウォッチ。動くものを見張る",ex:"Are they watching TV now?",exjp:"彼らは今テレビを見ていますか。",deck:"m1"},
{w:"give",jp:"与える・あげる",hook:"ギブアップ＝諦めて明け渡す。ギブ&テイク",ex:"My father gave me a watch.",exw:"gave",exjp:"父は私に時計をくれた。",deck:"m1"},
{w:"call",jp:"呼ぶ・電話する",hook:"コールセンター＝電話を受ける所",ex:"We call the dog Pochi.",exjp:"その犬をポチと呼ぶ。",deck:"m1"},
{w:"read",jp:"読む",hook:"リーダー（reader）＝読む人・読む機械",ex:"This book is read by many people.",exjp:"この本は多くの人に読まれている。",deck:"m1"},
{w:"speak",jp:"話す",hook:"スピーカー＝話す装置",ex:"It is difficult for me to speak English.",exjp:"英語を話すのは私には難しい。",deck:"m1"},
{w:"sleep",jp:"眠る",hook:"PCのスリープモード＝眠る",ex:"Look at that sleeping baby.",exjp:"あの眠っている赤ちゃんを見て。",deck:"m1"},
{w:"want",jp:"欲しい・〜してほしい",hook:"指名手配のWANTED＝警察が「欲しがっている」",ex:"I want you to read this book.",exjp:"あなたにこの本を読んでほしい。",deck:"m1"},
{w:"stop",jp:"止まる・やめる",hook:"ストップ",ex:"He stopped singing.",exjp:"歌うのをやめた。",deck:"m1"},
{w:"rain",jp:"雨が降る",hook:"レインコート",ex:"If it rains tomorrow, I will stay home.",exjp:"明日雨なら家にいる。",deck:"m1"},
{w:"money",jp:"お金",hook:"マネー",ex:"If I had money, I would buy the car.",exjp:"お金があれば買うのに。",deck:"m1"},
{w:"clean",jp:"掃除する",hook:"クリーニング＝きれいにすること",ex:"This room is cleaned every day.",exjp:"この部屋は毎日掃除される。",deck:"m1"},
{w:"get",jp:"手に入れる・着く",hook:"ゲットする。get to 駅＝駅に着く、の顔もある",ex:"I don't know how to get to the station.",exjp:"駅への行き方が分からない。",deck:"m1"},
// ===== 中2レベル =====
{w:"take",jp:"取る・（風呂に）入る",hook:"テイクアウト＝取って持ち出す。take a bath＝風呂を取る→入る",ex:"She was taking a bath when I called.",exw:"taking",exjp:"電話した時、お風呂に入っていた。",deck:"m2"},
{w:"teach",jp:"教える",hook:"ティーチャー＝teach+er＝教える人",ex:"She teaches English.",exjp:"彼女は英語を教えている。",deck:"m2"},
{w:"write",jp:"書く",hook:"ライター（writer）＝書く人",ex:"This is the book which he wrote.",exw:"wrote",exjp:"これは彼が書いた本だ。",deck:"m2"},
{w:"meet",jp:"会う",hook:"ミーティング＝会うこと",ex:"Walking in the park, I met an old friend.",exw:"met",exjp:"公園を歩いていて旧友に会った。",deck:"m2"},
{w:"keep",jp:"保つ・〜のままでいる",hook:"キープする＝そのまま保つ",ex:"I kept silent.",exw:"kept",exjp:"私は黙ったままでいた。",deck:"m2"},
{w:"visit",jp:"訪れる",hook:"ビジター＝訪れる人（ビジター料金）",ex:"I am going to visit Kyoto next week.",exjp:"来週京都を訪れる予定だ。",deck:"m2"},
{w:"enjoy",jp:"楽しむ",hook:"エンジョイ",ex:"He enjoyed playing tennis.",exjp:"テニスを楽しんだ。",deck:"m2"},
{w:"stay",jp:"とどまる・いる",hook:"ホームステイ＝よその家にとどまる",ex:"I will stay home.",exjp:"家にいます。",deck:"m2"},
{w:"break",jp:"壊す・割る",hook:"ブレイクタイム＝作業を壊す→休憩。「壊す」が本体",ex:"The window was broken by him.",exw:"broken",exjp:"窓は彼に割られた。",deck:"m2"},
{w:"finish",jp:"終える",hook:"フィニッシュ",ex:"He has just finished his homework.",exjp:"ちょうど宿題を終えたところだ。",deck:"m2"},
{w:"wait",jp:"待つ",hook:"ウェイター＝客を待つ人・給仕",ex:"Wait for me at the station.",exjp:"駅で待ってて。",deck:"m2"},
{w:"leave",jp:"出発する・去る・残す",hook:"家をleave＝出る。メッセージをleave＝残す。「その場から切り離す」イメージ",ex:"The train had already left.",exw:"left",exjp:"電車はすでに出発していた。",deck:"m2"},
{w:"arrive",jp:"到着する",hook:"空港のArrival（アライバル）＝到着ロビー",ex:"He arrived late.",exjp:"彼は遅れて到着した。",deck:"m2"},
{w:"borrow",jp:"借りる",hook:"貸すのlend（レンタルの親戚）とペア。borrowは借りる側",ex:"Can I borrow your pen?",exjp:"ペンを借りてもいい？",deck:"m2"},
{w:"forget",jp:"忘れる",hook:"忘れな草＝forget-me-not（私を忘れないで）",ex:"Don't forget your umbrella.",exjp:"傘を忘れないで。",deck:"m2"},
{w:"remember",jp:"覚えている・思い出す",hook:"リマインダー（reminder）＝rememberさせる通知",ex:"I remember his name.",exjp:"彼の名前を覚えている。",deck:"m2"},
{w:"understand",jp:"理解する",hook:"アンダースタンド。了解の「アンダスタン？」",ex:"I understand your point.",exjp:"言いたいことは分かる。",deck:"m2"},
{w:"worry",jp:"心配する",hook:"No worries（ノーウォーリーズ）＝心配ご無用",ex:"Don't worry about it.",exjp:"心配しないで。",deck:"m2"},
{w:"busy",jp:"忙しい",hook:"ビジネス（business）＝busy+ness＝忙しいこと",ex:"He will be busy tomorrow.",exjp:"彼は明日忙しいだろう。",deck:"m2"},
{w:"tall",jp:"背が高い",hook:"スタバのトールサイズ＝大きいカップ",ex:"He is as tall as me.",exjp:"彼は私と同じくらい背が高い。",deck:"m2"},
{w:"late",jp:"遅い・遅れた",hook:"レイトショー＝遅い時間の上映",ex:"Do you know the reason why he was late?",exjp:"彼が遅刻した理由を知ってる？",deck:"m2"},
{w:"sick",jp:"病気の",hook:"シックハウス症候群＝家が原因の「病気」",ex:"He must be sick.",exjp:"彼は病気に違いない。",deck:"m2"},
{w:"beautiful",jp:"美しい",hook:"ビューティーサロンのbeauty+ful＝美しさで満ちた",ex:"The pictures she took were beautiful.",exjp:"彼女が撮った写真は美しかった。",deck:"m2"},
{w:"homework",jp:"宿題",hook:"home+work＝家の仕事",ex:"He has just finished his homework.",exjp:"ちょうど宿題を終えたところ。",deck:"m2"},
// ===== 中3レベル =====
{w:"pass",jp:"通る・合格する",hook:"パスする＝通る。試験を通過→合格",ex:"I would have passed the exam.",exjp:"試験に受かっていたのに。",deck:"m3"},
{w:"born",jp:"生まれる（be born）",hook:"「Tokyo-born」＝東京生まれ。be bornで丸ごと覚える",ex:"This is the town where I was born.",exjp:"私が生まれた町だ。",deck:"m3"},
{w:"silent",jp:"静かな・黙った",hook:"サイレント映画＝無声映画",ex:"I kept silent.",exjp:"黙ったままでいた。",deck:"m3"},
{w:"tired",jp:"疲れた",hook:"tire＝疲れさせる。tired＝疲れさせられた→疲れた",ex:"He must have been tired.",exjp:"疲れていたに違いない。",deck:"m3"},
{w:"honest",jp:"正直な",hook:"オネスト。hを読まない仲間（hour＝アワーと同じ）",ex:"I think that he is honest.",exjp:"彼は正直だと思う。",deck:"m3"},
{w:"difficult",jp:"難しい",hook:"反対語はeasy（イージー）。テストの定番語",ex:"This question is more difficult than that one.",exjp:"この問題の方が難しい。",deck:"m3"},
{w:"reason",jp:"理由",hook:"リーズナブル＝理由が通る→納得できる値段",ex:"Do you know the reason why he was late?",exjp:"遅刻した理由を知ってる？",deck:"m3"},
{w:"exam",jp:"試験",hook:"examination（検査・試験）の略。健康診断もexam",ex:"I would have passed the exam.",exjp:"試験に受かっていたのに。",deck:"m3"},
{w:"expensive",jp:"（値段が）高い",hook:"ex（外へ）+pense（支払う）＝金が出ていく。経費＝expenses",ex:"This watch is too expensive.",exjp:"この時計は高すぎる。",deck:"m3"},
{w:"famous",jp:"有名な",hook:"フェイマス。fame（名声）+ous",ex:"Kyoto is famous for its temples.",exjp:"京都は寺で有名だ。",deck:"m3"},
{w:"popular",jp:"人気のある",hook:"ポップス＝popular music＝人気の音楽",ex:"This song is popular among young people.",exjp:"この歌は若者に人気だ。",deck:"m3"},
{w:"dangerous",jp:"危険な",hook:"デンジャラス。danger（デンジャー）+ous",ex:"Swimming here is dangerous.",exjp:"ここで泳ぐのは危険だ。",deck:"m3"},
{w:"useful",jp:"役に立つ",hook:"use（使う）+ful（満ちた）",ex:"This tool is very useful.",exjp:"この道具はとても役に立つ。",deck:"m3"},
{w:"experience",jp:"経験",hook:"UX＝User eXperience（ユーザー体験）。ゲームの経験値＝EXP",ex:"I have experience in teaching.",exjp:"教えた経験がある。",deck:"m3"},
{w:"foreign",jp:"外国の",hook:"FX＝Foreign Exchange＝外国為替",ex:"She speaks three foreign languages.",exjp:"3つの外国語を話す。",deck:"m3"},
{w:"receive",jp:"受け取る",hook:"バレーのレシーブ＝相手の球を受ける",ex:"I received an email from him.",exjp:"彼からメールを受け取った。",deck:"m3"},
{w:"decide",jp:"決める",hook:"ディサイド。decision（ディシジョン）＝決定",ex:"I decided to study abroad.",exjp:"留学することを決めた。",deck:"m3"},
{w:"communicate",jp:"やりとりする・伝え合う",hook:"コミュニケーションの動詞形",ex:"We communicate by email.",exjp:"私たちはメールでやりとりする。",deck:"m3"},
// ===== 高校基礎レベル =====
{w:"environment",jp:"環境",hook:"開発環境＝environment。環境変数のenv",ex:"We should protect the environment.",exjp:"環境を守るべきだ。",deck:"h1"},
{w:"increase",jp:"増える・増やす",hook:"プログラミングのインクリメント（increment＝1増やす）の親戚",ex:"Sales increased last year.",exjp:"昨年、売上が増えた。",deck:"h1"},
{w:"opinion",jp:"意見",hook:"オピニオンリーダー＝意見で引っ張る人",ex:"In my opinion, this plan is better.",exjp:"私の意見ではこの案の方がいい。",deck:"h1"},
{w:"express",jp:"表現する",hook:"ex（外へ）+press（押す）＝気持ちを外に押し出す。急行（エクスプレス）も「押し出される速さ」",ex:"It is hard to express my feelings.",exjp:"気持ちを表現するのは難しい。",deck:"h1"},
{w:"society",jp:"社会",hook:"ソサエティ。SNSのソーシャル（social）の名詞形",ex:"We live in an aging society.",exjp:"私たちは高齢化社会に生きている。",deck:"h1"},
{w:"improve",jp:"改善する・上達する",hook:"インプルーブ。カイゼンの英訳でよく出る",ex:"I want to improve my English.",exjp:"英語を上達させたい。",deck:"h1"},
{w:"provide",jp:"提供する",hook:"プロバイダー（provider）＝ネット接続を提供する会社",ex:"The hotel provides free breakfast.",exjp:"そのホテルは無料の朝食を提供する。",deck:"h1"},
{w:"offer",jp:"申し出る・提供する",hook:"転職のオファー＝仕事の申し出",ex:"They offered me a job.",exjp:"仕事をオファーされた。",deck:"h1"},
{w:"require",jp:"必要とする・要求する",hook:"入力フォームのrequired＝必須（要求されている）",ex:"This job requires English skills.",exjp:"この仕事は英語力が必要だ。",deck:"h1"},
{w:"suggest",jp:"提案する",hook:"検索のサジェスト機能＝候補の提案",ex:"He suggested a new plan.",exjp:"彼は新しい案を提案した。",deck:"h1"},
{w:"avoid",jp:"避ける",hook:"アボイド。void（空っぽ）にする→近寄らず無にする",ex:"Avoid using difficult words.",exjp:"難しい語を使うのを避けて。",deck:"h1"},
{w:"allow",jp:"許可する",hook:"スマホの許可ダイアログの「Allow」＝許可",ex:"My parents allowed me to go.",exjp:"両親は行くのを許してくれた。",deck:"h1"},
{w:"compare",jp:"比較する",hook:"比較サイトのcompare。com（共に）+pare（並べる）",ex:"Compare the two plans.",exjp:"2つの案を比較して。",deck:"h1"},
{w:"consider",jp:"よく考える・検討する",hook:"「ご検討ください」＝Please consider",ex:"We should consider his idea.",exjp:"彼の案を検討すべきだ。",deck:"h1"},
{w:"effort",jp:"努力",hook:"研究者の「エフォート率」＝仕事にかける労力の割合",ex:"Success needs effort.",exjp:"成功には努力が要る。",deck:"h1"},
{w:"opportunity",jp:"機会",hook:"オポチュニティ。チャンスのかしこまった版",ex:"This is a good opportunity to learn.",exjp:"学ぶ良い機会だ。",deck:"h1"},
{w:"available",jp:"利用できる・手に入る",hook:"AWSのアベイラビリティゾーン＝利用可能な区画",ex:"This service is available for free.",exjp:"このサービスは無料で利用できる。",deck:"h1"},
{w:"various",jp:"さまざまな",hook:"バラエティ（variety）番組＝いろいろ、の形容詞",ex:"There are various ways to learn.",exjp:"学ぶ方法はいろいろある。",deck:"h1"},
{w:"similar",jp:"似ている",hook:"類似画像検索＝similar images",ex:"My idea is similar to yours.",exjp:"私の案はあなたのと似ている。",deck:"h1"},
{w:"recent",jp:"最近の",hook:"スマホの「最近使ったアプリ」＝Recents",ex:"Recent studies show interesting results.",exjp:"最近の研究は面白い結果を示している。",deck:"h1"},
// ===== 高校標準レベル =====
{w:"reduce",jp:"減らす",hook:"3RのReduce＝ごみを減らす",ex:"We need to reduce costs.",exjp:"コストを減らす必要がある。",deck:"h2"},
{w:"benefit",jp:"利益・恩恵",hook:"福利厚生＝benefits。ベネフィット",ex:"Exercise has many benefits.",exjp:"運動には多くの利点がある。",deck:"h2"},
{w:"demand",jp:"需要・要求（する）",hook:"オンデマンド＝要求に応じて配信",ex:"Demand for AI engineers is growing.",exjp:"AIエンジニアの需要が伸びている。",deck:"h2"},
{w:"occur",jp:"起こる・発生する",hook:"エラー画面の「An error occurred」＝エラーが発生しました",ex:"The accident occurred at night.",exjp:"事故は夜に起きた。",deck:"h2"},
{w:"obtain",jp:"手に入れる・取得する",hook:"ob+tain（保持）＝手に入れて保持する。getのかたい版",ex:"You need to obtain a license.",exjp:"免許を取得する必要がある。",deck:"h2"},
{w:"maintain",jp:"維持する",hook:"メンテナンス（maintenance）＝maintainすること",ex:"It is hard to maintain motivation.",exjp:"やる気を維持するのは大変だ。",deck:"h2"},
{w:"establish",jp:"設立する・確立する",hook:"会社概要の「Established 1990」＝1990年設立",ex:"The company was established in 1990.",exjp:"その会社は1990年に設立された。",deck:"h2"},
{w:"contribute",jp:"貢献する",hook:"OSSのコントリビューター＝プロジェクトに貢献する人",ex:"He contributed to the project.",exjp:"彼はプロジェクトに貢献した。",deck:"h2"},
{w:"appreciate",jp:"感謝する・価値を分かる",hook:"ビジネス英語の定番「I appreciate your help」＝感謝します",ex:"I appreciate your help.",exjp:"助けてくれて感謝します。",deck:"h2"},
{w:"encourage",jp:"励ます・促す",hook:"en（中に入れる）+courage（勇気）＝勇気を注ぎ込む",ex:"My teacher encouraged me.",exjp:"先生が励ましてくれた。",deck:"h2"},
{w:"estimate",jp:"見積もる",hook:"開発工数のエスティメート＝見積もり",ex:"We estimated the cost.",exjp:"費用を見積もった。",deck:"h2"},
{w:"evaluate",jp:"評価する",hook:"エバリュエーション＝評価。value（価値）を測る",ex:"The teacher evaluated my essay.",exjp:"先生が私の作文を評価した。",deck:"h2"},
{w:"significant",jp:"重要な・大きな",hook:"統計の「有意差」＝significant difference",ex:"There is a significant difference.",exjp:"大きな差がある。",deck:"h2"},
{w:"sufficient",jp:"十分な",hook:"エラーの「insufficient memory」＝メモリ不足（in＝否定）",ex:"We don't have sufficient time.",exjp:"十分な時間がない。",deck:"h2"},
{w:"apparent",jp:"明らかな",hook:"appear（現れる）の親戚＝見た目に明らか",ex:"It was apparent that he was tired.",exjp:"彼が疲れているのは明らかだった。",deck:"h2"},
{w:"assume",jp:"思い込む・前提とする",hook:"仮説マッピングのassumption（思い込み・仮定）の動詞形",ex:"I assumed he was right.",exjp:"彼が正しいと思い込んでいた。",deck:"h2"},
{w:"affect",jp:"影響を与える",hook:"エフェクト（effect＝効果）の動詞側。「AがBにaffectする」",ex:"The weather affects my mood.",exjp:"天気は気分に影響する。",deck:"h2"},
{w:"determine",jp:"決定する",hook:"ターミネーター＝終わらせる者。term（限界）を定める→決定",ex:"We determined the price.",exjp:"価格を決定した。",deck:"h2"},

// ============================================================
// ここから分野別（kind:"topic"）。レベル診断には混ぜない。
// フックは「日本語の中に既にあるカタカナ」から繋げる方針。
// ============================================================

// ===== AWS・クラウド =====
{w:"deploy",jp:"配置する・展開する",hook:"デプロイ。そのまま使っている言葉",ex:"We deploy the app to the cloud.",exjp:"アプリをクラウドへ展開する。",deck:"aws"},
{w:"provision",jp:"用意する・払い出す",hook:"プロビジョニング。resourceを「あてがう」",ex:"We provision the servers automatically.",exjp:"サーバーを自動で払い出す。",deck:"aws"},
{w:"redundancy",jp:"冗長性",hook:"リダンダント。同じものを2つ持って備えること",ex:"Redundancy prevents a single failure.",exjp:"冗長性が単一障害を防ぐ。",deck:"aws"},
{w:"latency",jp:"遅延",hook:"レイテンシー。応答までの待ち時間",ex:"Low latency is important for users.",exjp:"利用者には低遅延が重要だ。",deck:"aws"},
{w:"throughput",jp:"処理量",hook:"スループット。through（通り抜ける）put（置く）量",ex:"We measured the throughput per second.",exjp:"毎秒の処理量を測った。",deck:"aws"},
{w:"outage",jp:"停止・障害",hook:"out（外れている）＋age（状態）。落ちている状態",ex:"The outage lasted two hours.",exjp:"障害は2時間続いた。",deck:"aws"},
{w:"mitigate",jp:"緩和する",hook:"リスクを和らげる。mitigation は提案書に必ず出る",ex:"We mitigate the risk with backups.",exjp:"バックアップでリスクを緩和する。",deck:"aws"},
{w:"compliance",jp:"法令順守",hook:"コンプライアンス。comply（従う）の名詞",ex:"The design meets compliance requirements.",exjp:"設計は法令順守の要件を満たす。",deck:"aws"},
{w:"encrypt",jp:"暗号化する",hook:"crypt＝暗号。暗号通貨の crypto と同じ",ex:"We encrypt the data at rest.",exjp:"保存時にデータを暗号化する。",deck:"aws"},
{w:"quota",jp:"上限枠",hook:"クォータ。割り当てられた量",ex:"We hit the service quota.",exjp:"サービスの上限枠に達した。",deck:"aws"},
{w:"onboarding",jp:"導入・受け入れ",hook:"オンボーディング。board（船）に乗せる",ex:"Customer onboarding takes two weeks.",exjp:"顧客の受け入れには2週間かかる。",deck:"aws"},
{w:"resilient",jp:"復元力のある",hook:"レジリエンス。折れても戻る強さ",ex:"The system is resilient to failure.",exjp:"そのシステムは障害に強い。",deck:"aws"},

// ===== ビジネス検討 =====
{w:"feasibility",jp:"実現可能性",hook:"フィジビリティスタディ。そもそもできるのか",ex:"We checked the feasibility first.",exjp:"まず実現可能性を確かめた。",deck:"biz"},
{w:"stakeholder",jp:"関係者",hook:"ステークホルダー。stake（杭）を打っている人",ex:"We aligned with the stakeholders.",exjp:"関係者と認識を合わせた。",deck:"biz"},
{w:"assumption",jp:"前提・仮定",hook:"assume（仮定する）の名詞。仮説マッピングで使う",ex:"The plan rests on one assumption.",exjp:"計画は1つの前提に乗っている。",deck:"biz"},
{w:"baseline",jp:"基準線",hook:"ベースライン。導入する前に測っておく値",ex:"We measured the baseline before launch.",exjp:"開始前に基準線を測った。",deck:"biz"},
{w:"procurement",jp:"調達",hook:"調達仕様書＝procurement document",ex:"The procurement process takes months.",exjp:"調達の手続きには数か月かかる。",deck:"biz"},
{w:"deliverable",jp:"成果物",hook:"deliver（届ける）もの＝納品するもの",ex:"We listed every deliverable.",exjp:"成果物を全部書き出した。",deck:"biz"},
{w:"scope",jp:"範囲",hook:"スコープ。見える範囲・やる範囲",ex:"We agreed on the project scope.",exjp:"案件の範囲に合意した。",deck:"biz"},
{w:"constraint",jp:"制約",hook:"制約条件。締め付けて動ける幅を決めるもの",ex:"Budget is the main constraint.",exjp:"予算が主な制約だ。",deck:"biz"},
{w:"rationale",jp:"根拠",hook:"rational（合理的）の名詞。なぜそうしたか",ex:"Please explain the rationale.",exjp:"根拠を説明してください。",deck:"biz"},
{w:"tradeoff",jp:"得失・引き換え",hook:"トレードオフ。取引して何かを手放す",ex:"There is a tradeoff between cost and speed.",exjp:"費用と速さは引き換えになる。",deck:"biz"},
{w:"prioritize",jp:"優先順位をつける",hook:"プライオリティ（priority）の動詞",ex:"We prioritize the top three issues.",exjp:"上位3つの課題を優先する。",deck:"biz"},
{w:"validate",jp:"検証する",hook:"バリデーション。妥当かどうかを確かめる",ex:"We validate the hypothesis with users.",exjp:"利用者に当てて仮説を検証する。",deck:"biz"},

// ===== 経済ニュース =====
{w:"inflation",jp:"物価上昇",hook:"インフレ。inflate（膨らませる）の名詞",ex:"Inflation slowed last month.",exjp:"先月、物価上昇は鈍化した。",deck:"econ"},
{w:"yield",jp:"利回り・生み出す",hook:"収穫量のyield。お金が生む量＝利回り",ex:"Bond yields rose sharply.",exjp:"債券の利回りが急上昇した。",deck:"econ"},
{w:"recession",jp:"景気後退",hook:"リセッション。re（後ろへ）＋cede（進む）",ex:"The economy entered a recession.",exjp:"経済は景気後退に入った。",deck:"econ"},
{w:"tariff",jp:"関税",hook:"タリフ。輸入品にかける税",ex:"New tariffs raised prices.",exjp:"新しい関税が価格を押し上げた。",deck:"econ"},
{w:"revenue",jp:"売上",hook:"レベニュー。re（戻って）venue（来る）＝入ってくるお金",ex:"Revenue grew ten percent.",exjp:"売上が10%伸びた。",deck:"econ"},
{w:"margin",jp:"利益率",hook:"マージン。余白＝手元に残る取り分",ex:"The margin shrank this quarter.",exjp:"今四半期は利益率が縮んだ。",deck:"econ"},
{w:"forecast",jp:"予測する",hook:"フォーキャスト。fore（先に）cast（投げる）",ex:"They forecast slower growth.",exjp:"成長の鈍化を予測している。",deck:"econ"},
{w:"surplus",jp:"黒字・余剰",hook:"sur（上に）plus（足す）＝余った分",ex:"The trade surplus widened.",exjp:"貿易黒字が拡大した。",deck:"econ"},
{w:"deficit",jp:"赤字・不足",hook:"デフィシット。surplus の反対で足りない側",ex:"The budget deficit grew.",exjp:"財政赤字が拡大した。",deck:"econ"},
{w:"merger",jp:"合併",hook:"merge（マージする）の名詞",ex:"The merger was approved.",exjp:"合併が承認された。",deck:"econ"},
{w:"volatile",jp:"変動が激しい",hook:"ボラティリティ。飛びやすい・揺れやすい",ex:"The market was volatile.",exjp:"市場は変動が激しかった。",deck:"econ"},
{w:"quarterly",jp:"四半期の",hook:"クォーター（4分の1）＝3か月ごと",ex:"Quarterly earnings beat estimates.",exjp:"四半期決算は予想を上回った。",deck:"econ"},

// ===== アートの表現 =====
{w:"composition",jp:"構図",hook:"コンポジション。compose（組み立てる）の名詞",ex:"The composition draws the eye.",exjp:"その構図が視線を引く。",deck:"art"},
{w:"contrast",jp:"対比",hook:"コントラスト。明暗や色の差",ex:"The contrast is very strong.",exjp:"対比がとても強い。",deck:"art"},
{w:"texture",jp:"質感",hook:"テクスチャ。表面の手ざわり",ex:"The texture looks rough.",exjp:"質感が粗く見える。",deck:"art"},
{w:"hue",jp:"色合い",hook:"HSLのH。色そのものの方向",ex:"The hue shifts to blue.",exjp:"色合いが青へ寄る。",deck:"art"},
{w:"saturation",jp:"彩度",hook:"サチュレーション。色の濃さ・飽和",ex:"Lower the saturation a little.",exjp:"彩度を少し下げて。",deck:"art"},
{w:"depict",jp:"描く",hook:"picture（絵）と同じ語源。絵にする",ex:"The painting depicts a storm.",exjp:"その絵は嵐を描いている。",deck:"art"},
{w:"figurative",jp:"具象の",hook:"figure（形・人の姿）の形容詞",ex:"His work is figurative, not abstract.",exjp:"彼の作品は抽象でなく具象だ。",deck:"art"},
{w:"abstract",jp:"抽象的な",hook:"アブストラクト。形から離れている",ex:"The style is abstract.",exjp:"その様式は抽象的だ。",deck:"art"},
{w:"perspective",jp:"遠近法・視点",hook:"パースをつける。見る位置",ex:"The perspective feels deep.",exjp:"遠近感が深く感じられる。",deck:"art"},
{w:"render",jp:"描画する・表現する",hook:"レンダリング。光や色を絵にする",ex:"The light is rendered softly.",exjp:"光がやわらかく描かれている。",deck:"art"},
{w:"evoke",jp:"呼び起こす",hook:"voice（声）と同語源。引き出す",ex:"The colors evoke calm.",exjp:"その色は静けさを呼び起こす。",deck:"art"},
{w:"palette",jp:"色の組み合わせ",hook:"パレット。使う色の一式",ex:"The palette is limited to three colors.",exjp:"色数は3色に絞られている。",deck:"art"},

// ===== 車・運転 =====
{w:"steering",jp:"操舵・ハンドル操作",hook:"ステアリング。steer（舵を取る）",ex:"The steering feels light.",exjp:"ハンドルが軽く感じる。",deck:"car"},
{w:"suspension",jp:"サスペンション",hook:"suspend（吊る）の名詞。車体を吊っている",ex:"The suspension absorbs bumps.",exjp:"サスが段差を吸収する。",deck:"car"},
{w:"torque",jp:"トルク・回す力",hook:"トルク。加速の押し出す力",ex:"The engine has high torque.",exjp:"そのエンジンはトルクが太い。",deck:"car"},
{w:"displacement",jp:"排気量",hook:"place（置く）を押しのける量",ex:"The engine displacement is two liters.",exjp:"排気量は2リッターだ。",deck:"car"},
{w:"transmission",jp:"変速機",hook:"トランスミッション。transmit（伝える）",ex:"The transmission shifts smoothly.",exjp:"変速がなめらかだ。",deck:"car"},
{w:"brake",jp:"ブレーキをかける",hook:"ブレーキ。名詞でも動詞でも使う",ex:"He braked hard before the corner.",exjp:"彼はコーナー手前で強くブレーキをかけた。",deck:"car"},
{w:"mileage",jp:"走行距離・燃費",hook:"mile（マイル）＋age（量）",ex:"The car has low mileage.",exjp:"その車は走行距離が短い。",deck:"car"},
{w:"exhaust",jp:"排気",hook:"エキゾースト。出し尽くす",ex:"The exhaust note is loud.",exjp:"排気音が大きい。",deck:"car"},
{w:"chassis",jp:"車体・骨格",hook:"シャシー。骨組みの部分",ex:"The chassis is very rigid.",exjp:"車体がとても剛性が高い。",deck:"car"},
{w:"handling",jp:"操縦性",hook:"ハンドリング。handle（扱う）の名詞",ex:"The handling is sharp.",exjp:"操縦性が鋭い。",deck:"car"},
{w:"cornering",jp:"コーナリング",hook:"corner（角）を曲がること",ex:"Cornering is stable at speed.",exjp:"高速でも安定して曲がる。",deck:"car"},
{w:"aerodynamics",jp:"空力",hook:"エアロ。air（空気）＋dynamics（力学）",ex:"Aerodynamics reduce drag.",exjp:"空力が抗力を減らす。",deck:"car"},
// ===== 動詞＋名詞の組み合わせ（alt＝日本語から直訳すると選んでしまう方） =====
{w:"make a decision",jp:"決定を下す",alt:"do a decision",hook:"「決定をする」でもdoは使わない。無かったものを作り出す側のmake",ex:"We need to make a decision by Friday.",exjp:"金曜までに決定する必要がある。",deck:"col-vn"},
{w:"take measures",jp:"対策を取る",alt:"do measures",hook:"日本語の「取る」がそのままtake。measureは「措置」",ex:"We will take measures to prevent it.",exjp:"再発防止の対策を取ります。",deck:"col-vn"},
{w:"reach an agreement",jp:"合意に達する",alt:"arrive an agreement",hook:"reachは「手が届く」。arriveは後ろにatが必要になる",ex:"They finally reached an agreement.",exjp:"ようやく合意に達した。",exw:"reached",deck:"col-vn"},
{w:"raise a concern",jp:"懸念を挙げる",alt:"rise a concern",hook:"raiseは「他の物を上げる」、riseは「自分が上がる」。挙げるのは他動詞のraise",ex:"He raised a concern about the cost.",exjp:"彼が費用の懸念を挙げた。",exw:"raised",deck:"col-vn"},
{w:"meet the deadline",jp:"締切に間に合わせる",alt:"catch the deadline",hook:"meetは「会う」だけでなく「要求に応える」。条件を満たす時もmeet",ex:"We can still meet the deadline.",exjp:"まだ締切に間に合う。",deck:"col-vn"},
{w:"address an issue",jp:"課題に対処する",alt:"address to an issue",hook:"アドレス＝宛先を向けること。他動詞なのでtoを入れない",ex:"We should address an issue early.",exjp:"課題には早めに対処すべきだ。",deck:"col-vn"},
{w:"hold a meeting",jp:"会議を開く",alt:"open a meeting",hook:"日本語は「開く」だが、催すという意味のholdを使う",ex:"We will hold a meeting next week.",exjp:"来週会議を開きます。",deck:"col-vn"},
{w:"place an order",jp:"発注する",alt:"put an order",hook:"placeは「置く」。注文を先方に置く＝発注",ex:"We placed an order yesterday.",exjp:"昨日発注した。",exw:"placed",deck:"col-vn"},
{w:"conduct a survey",jp:"調査を実施する",alt:"make a survey",hook:"コンダクター（指揮者）。仕切って実施する側",ex:"We will conduct a survey in May.",exjp:"5月に調査を実施する。",deck:"col-vn"},
{w:"draw a conclusion",jp:"結論を導く",alt:"pull a conclusion",hook:"drawは「線を引く・描く」。線を引いて結論まで持っていく",ex:"It is too early to draw a conclusion.",exjp:"結論を出すには早すぎる。",deck:"col-vn"},
{w:"pay attention",jp:"注意を払う",alt:"pay an attention",hook:"日本語の「払う」と同じ。attentionは数えないのでaを付けない",ex:"Please pay attention to the numbers.",exjp:"数字に注意を払ってください。",deck:"col-vn"},
{w:"take a look",jp:"ちょっと見る",alt:"see a look",hook:"Take a look＝「ちょっと見て」。メールの定型",ex:"Could you take a look at this?",exjp:"これを見ていただけますか。",deck:"col-vn"},
// ===== 動詞＋前置詞の組み合わせ（altは日本語の助詞から選んでしまう方） =====
{w:"depend on",jp:"〜に依存する",alt:"depend to",hook:"ディペンデント。相手の上に乗っている＝on",ex:"The result depends on the data.",exjp:"結果はデータ次第だ。",exw:"depends",deck:"col-prep"},
{w:"consist of",jp:"〜から成る",alt:"consist from",hook:"日本語は「から」だがfromではなくof。中身を指すof",ex:"The team consists of five people.",exjp:"チームは5人から成る。",exw:"consists",deck:"col-prep"},
{w:"result in",jp:"結果として〜になる",alt:"result to",hook:"結果の中へ入っていく＝in。原因を言うときは result from",ex:"The delay resulted in extra cost.",exjp:"遅れが追加費用を生んだ。",exw:"resulted",deck:"col-prep"},
{w:"focus on",jp:"〜に集中する",alt:"focus at",hook:"フォーカス。的の上にぴったり乗せる＝on",ex:"Let us focus on the main issue.",exjp:"主要な課題に集中しよう。",deck:"col-prep"},
{w:"refer to",jp:"〜を参照する",alt:"refer at",hook:"リファレンス。矢印を向ける＝to",ex:"Please refer to page ten.",exjp:"10ページを参照してください。",deck:"col-prep"},
{w:"comply with",jp:"〜に従う",alt:"comply to",hook:"コンプライアンス。規則と一緒に歩く＝with",ex:"We must comply with the rules.",exjp:"規則に従わなければならない。",deck:"col-prep"},
{w:"account for",jp:"〜を占める・説明する",alt:"account of",hook:"アカウント（勘定）。そのぶんを勘定に入れる＝for",ex:"Labor costs account for half of it.",exjp:"人件費が半分を占める。",deck:"col-prep"},
{w:"deal with",jp:"〜を扱う・対応する",alt:"deal to",hook:"ディール（取引）。相手と組んで扱う＝with",ex:"I will deal with the complaint.",exjp:"そのクレームには私が対応する。",deck:"col-prep"},
{w:"discuss the issue",jp:"その課題について話し合う",alt:"discuss about the issue",hook:"日本語の「について」でaboutを入れたくなるが不要。discussは他動詞",ex:"Let us discuss the issue tomorrow.",exjp:"明日その課題を話し合おう。",deck:"col-prep"},
{w:"attend the meeting",jp:"会議に出席する",alt:"attend to the meeting",hook:"日本語の「に」でtoを入れたくなるが不要。attend toは「対応する」で別の意味になる",ex:"I cannot attend the meeting today.",exjp:"今日は会議に出席できない。",deck:"col-prep"},
{w:"based on",jp:"〜に基づく",alt:"based in",hook:"ベース（土台）の上に乗る＝on。based inは「〜に拠点がある」で別の意味",ex:"The plan is based on last year's data.",exjp:"その計画は昨年のデータに基づく。",deck:"col-prep"},
{w:"look forward to",jp:"〜を楽しみにする",alt:"look forward for",hook:"メールの結びの定型。toが前置詞なので後ろは動詞のing形",ex:"I look forward to meeting you.",exjp:"お会いするのを楽しみにしています。",deck:"col-prep"},
];
