// 英単語amida用データ。中1→高校のレベル層×代表サンプルで「どの帯から崩れるか」を診断する
// 単語は無限にあるが頻度順で層になっているので、各レベルの代表語で診断が成立する
// w=単語 jp=意味 hook=覚えるフック ex/exjp=例文 exw=例文中の語形（変化形の時だけ） deck=レベルid
const WORD_DECKS=[
  {id:"m1",name:"中1レベル",desc:"毎日の動作の基本動詞"},
  {id:"m2",name:"中2レベル",desc:"やりとり・移動・気持ち"},
  {id:"m3",name:"中3レベル",desc:"経験・社会・少し抽象"},
  {id:"h1",name:"高校基礎レベル",desc:"提供する・要求する・利用できる"},
  {id:"h2",name:"高校標準レベル",desc:"評価する・維持する・有意な"},
];
const WORDS=[
// ===== 中1レベル =====
{w:"drink",jp:"飲む",hook:"ドリンク＝飲み物。「飲み物する」→飲む",ex:"I drink coffee every morning.",exjp:"毎朝コーヒーを飲む。",deck:"m1"},
{w:"live",jp:"住む",hook:"ライブ配信のlive＝「生の・生きている」。生きる場所→住む",ex:"She lives in Tokyo.",exjp:"彼女は東京に住んでいる。",deck:"m1"},
{w:"know",jp:"知っている",hook:"ノウハウ（know-how）＝やり方を知っていること",ex:"I know him.",exjp:"私は彼を知っている。",deck:"m1"},
{w:"run",jp:"走る",hook:"ランニング",ex:"She is running now.",exjp:"彼女は今走っている。",deck:"m1"},
{w:"swim",jp:"泳ぐ",hook:"スイミングスクール",ex:"She can swim fast.",exjp:"彼女は速く泳げる。",deck:"m1"},
{w:"open",jp:"開ける",hook:"オープン。開店＝店を開ける",ex:"Open the window.",exjp:"窓を開けなさい。",deck:"m1"},
{w:"study",jp:"勉強する",hook:"スタディサプリ",ex:"He didn't study last night.",exjp:"彼は昨夜勉強しなかった。",deck:"m1"},
{w:"work",jp:"働く",hook:"ワークライフバランス＝仕事と生活",ex:"You don't have to work today.",exjp:"今日は働かなくてもいい。",deck:"m1"},
{w:"buy",jp:"買う",hook:"バイヤー＝buy+er＝買う人",ex:"He went to the store to buy a book.",exjp:"本を買うために店へ行った。",deck:"m1"},
{w:"sing",jp:"歌う",hook:"シンガー＝sing+er＝歌う人",ex:"He stopped singing.",exjp:"彼は歌うのをやめた。",deck:"m1"},
{w:"see",jp:"見える・会う",hook:"シースルー＝透けて見える。see you＝また会おう",ex:"I'm looking forward to seeing her.",exjp:"彼女に会うのが楽しみだ。",deck:"m1"},
{w:"cook",jp:"料理する",hook:"クッキング",ex:"My mother was cooking.",exjp:"母は料理をしていた。",deck:"m1"},
{w:"watch",jp:"（動くものを）じっと見る",hook:"腕時計のウォッチ。動くものを見張る",ex:"Are they watching TV now?",exjp:"彼らは今テレビを見ていますか。",deck:"m1"},
{w:"give",jp:"与える・あげる",hook:"ギブアップ＝諦めて明け渡す。ギブ&テイク",ex:"My father gave me a watch.",exw:"gave",exjp:"父は私に時計をくれた。",deck:"m1"},
{w:"call",jp:"呼ぶ・電話する",hook:"コールセンター＝電話を受ける所",ex:"We call the dog Pochi.",exjp:"その犬をポチと呼ぶ。",deck:"m1"},
{w:"read",jp:"読む",hook:"リーダー（reader）＝読む人・読む機械",ex:"This book is read by many people.",exjp:"この本は多くの人に読まれている。",deck:"m1"},
{w:"speak",jp:"話す",hook:"スピーカー＝話す装置",ex:"It is difficult for me to speak English.",exjp:"英語を話すのは私には難しい。",deck:"m1"},
{w:"sleep",jp:"眠る",hook:"PCのスリープモード＝眠る",ex:"Look at that sleeping baby.",exjp:"あの眠っている赤ちゃんを見て。",deck:"m1"},
{w:"want",jp:"欲しい・〜してほしい",hook:"指名手配のWANTED＝警察が「欲しがっている」",ex:"I want you to read this book.",exjp:"あなたにこの本を読んでほしい。",deck:"m1"},
{w:"stop",jp:"止まる・やめる",hook:"ストップ",ex:"He stopped singing.",exjp:"歌うのをやめた。",deck:"m1"},
{w:"rain",jp:"雨が降る",hook:"レインコート",ex:"If it rains tomorrow, I will stay home.",exjp:"明日雨なら家にいる。",deck:"m1"},
{w:"money",jp:"お金",hook:"マネー",ex:"If I had money, I would buy the car.",exjp:"お金があれば買うのに。",deck:"m1"},
{w:"clean",jp:"掃除する",hook:"クリーニング＝きれいにすること",ex:"This room is cleaned every day.",exjp:"この部屋は毎日掃除される。",deck:"m1"},
{w:"get",jp:"手に入れる・着く",hook:"ゲットする。get to 駅＝駅に着く、の顔もある",ex:"I don't know how to get to the station.",exjp:"駅への行き方が分からない。",deck:"m1"},
// ===== 中2レベル =====
{w:"take",jp:"取る・（風呂に）入る",hook:"テイクアウト＝取って持ち出す。take a bath＝風呂を取る→入る",ex:"She was taking a bath when I called.",exw:"taking",exjp:"電話した時、お風呂に入っていた。",deck:"m2"},
{w:"teach",jp:"教える",hook:"ティーチャー＝teach+er＝教える人",ex:"She teaches English.",exjp:"彼女は英語を教えている。",deck:"m2"},
{w:"write",jp:"書く",hook:"ライター（writer）＝書く人",ex:"This is the book which he wrote.",exw:"wrote",exjp:"これは彼が書いた本だ。",deck:"m2"},
{w:"meet",jp:"会う",hook:"ミーティング＝会うこと",ex:"Walking in the park, I met an old friend.",exw:"met",exjp:"公園を歩いていて旧友に会った。",deck:"m2"},
{w:"keep",jp:"保つ・〜のままでいる",hook:"キープする＝そのまま保つ",ex:"I kept silent.",exw:"kept",exjp:"私は黙ったままでいた。",deck:"m2"},
{w:"visit",jp:"訪れる",hook:"ビジター＝訪れる人（ビジター料金）",ex:"I am going to visit Kyoto next week.",exjp:"来週京都を訪れる予定だ。",deck:"m2"},
{w:"enjoy",jp:"楽しむ",hook:"エンジョイ",ex:"He enjoyed playing tennis.",exjp:"テニスを楽しんだ。",deck:"m2"},
{w:"stay",jp:"とどまる・いる",hook:"ホームステイ＝よその家にとどまる",ex:"I will stay home.",exjp:"家にいます。",deck:"m2"},
{w:"break",jp:"壊す・割る",hook:"ブレイクタイム＝作業を壊す→休憩。「壊す」が本体",ex:"The window was broken by him.",exw:"broken",exjp:"窓は彼に割られた。",deck:"m2"},
{w:"finish",jp:"終える",hook:"フィニッシュ",ex:"He has just finished his homework.",exjp:"ちょうど宿題を終えたところだ。",deck:"m2"},
{w:"wait",jp:"待つ",hook:"ウェイター＝客を待つ人・給仕",ex:"Wait for me at the station.",exjp:"駅で待ってて。",deck:"m2"},
{w:"leave",jp:"出発する・去る・残す",hook:"家をleave＝出る。メッセージをleave＝残す。「その場から切り離す」イメージ",ex:"The train had already left.",exw:"left",exjp:"電車はすでに出発していた。",deck:"m2"},
{w:"arrive",jp:"到着する",hook:"空港のArrival（アライバル）＝到着ロビー",ex:"He arrived late.",exjp:"彼は遅れて到着した。",deck:"m2"},
{w:"borrow",jp:"借りる",hook:"貸すのlend（レンタルの親戚）とペア。borrowは借りる側",ex:"Can I borrow your pen?",exjp:"ペンを借りてもいい？",deck:"m2"},
{w:"forget",jp:"忘れる",hook:"忘れな草＝forget-me-not（私を忘れないで）",ex:"Don't forget your umbrella.",exjp:"傘を忘れないで。",deck:"m2"},
{w:"remember",jp:"覚えている・思い出す",hook:"リマインダー（reminder）＝rememberさせる通知",ex:"I remember his name.",exjp:"彼の名前を覚えている。",deck:"m2"},
{w:"understand",jp:"理解する",hook:"アンダースタンド。了解の「アンダスタン？」",ex:"I understand your point.",exjp:"言いたいことは分かる。",deck:"m2"},
{w:"worry",jp:"心配する",hook:"No worries（ノーウォーリーズ）＝心配ご無用",ex:"Don't worry about it.",exjp:"心配しないで。",deck:"m2"},
{w:"busy",jp:"忙しい",hook:"ビジネス（business）＝busy+ness＝忙しいこと",ex:"He will be busy tomorrow.",exjp:"彼は明日忙しいだろう。",deck:"m2"},
{w:"tall",jp:"背が高い",hook:"スタバのトールサイズ＝大きいカップ",ex:"He is as tall as me.",exjp:"彼は私と同じくらい背が高い。",deck:"m2"},
{w:"late",jp:"遅い・遅れた",hook:"レイトショー＝遅い時間の上映",ex:"Do you know the reason why he was late?",exjp:"彼が遅刻した理由を知ってる？",deck:"m2"},
{w:"sick",jp:"病気の",hook:"シックハウス症候群＝家が原因の「病気」",ex:"He must be sick.",exjp:"彼は病気に違いない。",deck:"m2"},
{w:"beautiful",jp:"美しい",hook:"ビューティーサロンのbeauty+ful＝美しさで満ちた",ex:"The pictures she took were beautiful.",exjp:"彼女が撮った写真は美しかった。",deck:"m2"},
{w:"homework",jp:"宿題",hook:"home+work＝家の仕事",ex:"He has just finished his homework.",exjp:"ちょうど宿題を終えたところ。",deck:"m2"},
// ===== 中3レベル =====
{w:"pass",jp:"通る・合格する",hook:"パスする＝通る。試験を通過→合格",ex:"I would have passed the exam.",exjp:"試験に受かっていたのに。",deck:"m3"},
{w:"born",jp:"生まれる（be born）",hook:"「Tokyo-born」＝東京生まれ。be bornで丸ごと覚える",ex:"This is the town where I was born.",exjp:"私が生まれた町だ。",deck:"m3"},
{w:"silent",jp:"静かな・黙った",hook:"サイレント映画＝無声映画",ex:"I kept silent.",exjp:"黙ったままでいた。",deck:"m3"},
{w:"tired",jp:"疲れた",hook:"tire＝疲れさせる。tired＝疲れさせられた→疲れた",ex:"He must have been tired.",exjp:"疲れていたに違いない。",deck:"m3"},
{w:"honest",jp:"正直な",hook:"オネスト。hを読まない仲間（hour＝アワーと同じ）",ex:"I think that he is honest.",exjp:"彼は正直だと思う。",deck:"m3"},
{w:"difficult",jp:"難しい",hook:"反対語はeasy（イージー）。テストの定番語",ex:"This question is more difficult than that one.",exjp:"この問題の方が難しい。",deck:"m3"},
{w:"reason",jp:"理由",hook:"リーズナブル＝理由が通る→納得できる値段",ex:"Do you know the reason why he was late?",exjp:"遅刻した理由を知ってる？",deck:"m3"},
{w:"exam",jp:"試験",hook:"examination（検査・試験）の略。健康診断もexam",ex:"I would have passed the exam.",exjp:"試験に受かっていたのに。",deck:"m3"},
{w:"expensive",jp:"（値段が）高い",hook:"ex（外へ）+pense（支払う）＝金が出ていく。経費＝expenses",ex:"This watch is too expensive.",exjp:"この時計は高すぎる。",deck:"m3"},
{w:"famous",jp:"有名な",hook:"フェイマス。fame（名声）+ous",ex:"Kyoto is famous for its temples.",exjp:"京都は寺で有名だ。",deck:"m3"},
{w:"popular",jp:"人気のある",hook:"ポップス＝popular music＝人気の音楽",ex:"This song is popular among young people.",exjp:"この歌は若者に人気だ。",deck:"m3"},
{w:"dangerous",jp:"危険な",hook:"デンジャラス。danger（デンジャー）+ous",ex:"Swimming here is dangerous.",exjp:"ここで泳ぐのは危険だ。",deck:"m3"},
{w:"useful",jp:"役に立つ",hook:"use（使う）+ful（満ちた）",ex:"This tool is very useful.",exjp:"この道具はとても役に立つ。",deck:"m3"},
{w:"experience",jp:"経験",hook:"UX＝User eXperience（ユーザー体験）。ゲームの経験値＝EXP",ex:"I have experience in teaching.",exjp:"教えた経験がある。",deck:"m3"},
{w:"foreign",jp:"外国の",hook:"FX＝Foreign Exchange＝外国為替",ex:"She speaks three foreign languages.",exjp:"3つの外国語を話す。",deck:"m3"},
{w:"receive",jp:"受け取る",hook:"バレーのレシーブ＝相手の球を受ける",ex:"I received an email from him.",exjp:"彼からメールを受け取った。",deck:"m3"},
{w:"decide",jp:"決める",hook:"ディサイド。decision（ディシジョン）＝決定",ex:"I decided to study abroad.",exjp:"留学することを決めた。",deck:"m3"},
{w:"communicate",jp:"やりとりする・伝え合う",hook:"コミュニケーションの動詞形",ex:"We communicate by email.",exjp:"私たちはメールでやりとりする。",deck:"m3"},
// ===== 高校基礎レベル =====
{w:"environment",jp:"環境",hook:"開発環境＝environment。環境変数のenv",ex:"We should protect the environment.",exjp:"環境を守るべきだ。",deck:"h1"},
{w:"increase",jp:"増える・増やす",hook:"プログラミングのインクリメント（increment＝1増やす）の親戚",ex:"Sales increased last year.",exjp:"昨年、売上が増えた。",deck:"h1"},
{w:"opinion",jp:"意見",hook:"オピニオンリーダー＝意見で引っ張る人",ex:"In my opinion, this plan is better.",exjp:"私の意見ではこの案の方がいい。",deck:"h1"},
{w:"express",jp:"表現する",hook:"ex（外へ）+press（押す）＝気持ちを外に押し出す。急行（エクスプレス）も「押し出される速さ」",ex:"It is hard to express my feelings.",exjp:"気持ちを表現するのは難しい。",deck:"h1"},
{w:"society",jp:"社会",hook:"ソサエティ。SNSのソーシャル（social）の名詞形",ex:"We live in an aging society.",exjp:"私たちは高齢化社会に生きている。",deck:"h1"},
{w:"improve",jp:"改善する・上達する",hook:"インプルーブ。カイゼンの英訳でよく出る",ex:"I want to improve my English.",exjp:"英語を上達させたい。",deck:"h1"},
{w:"provide",jp:"提供する",hook:"プロバイダー（provider）＝ネット接続を提供する会社",ex:"The hotel provides free breakfast.",exjp:"そのホテルは無料の朝食を提供する。",deck:"h1"},
{w:"offer",jp:"申し出る・提供する",hook:"転職のオファー＝仕事の申し出",ex:"They offered me a job.",exjp:"仕事をオファーされた。",deck:"h1"},
{w:"require",jp:"必要とする・要求する",hook:"入力フォームのrequired＝必須（要求されている）",ex:"This job requires English skills.",exjp:"この仕事は英語力が必要だ。",deck:"h1"},
{w:"suggest",jp:"提案する",hook:"検索のサジェスト機能＝候補の提案",ex:"He suggested a new plan.",exjp:"彼は新しい案を提案した。",deck:"h1"},
{w:"avoid",jp:"避ける",hook:"アボイド。void（空っぽ）にする→近寄らず無にする",ex:"Avoid using difficult words.",exjp:"難しい語を使うのを避けて。",deck:"h1"},
{w:"allow",jp:"許可する",hook:"スマホの許可ダイアログの「Allow」＝許可",ex:"My parents allowed me to go.",exjp:"両親は行くのを許してくれた。",deck:"h1"},
{w:"compare",jp:"比較する",hook:"比較サイトのcompare。com（共に）+pare（並べる）",ex:"Compare the two plans.",exjp:"2つの案を比較して。",deck:"h1"},
{w:"consider",jp:"よく考える・検討する",hook:"「ご検討ください」＝Please consider",ex:"We should consider his idea.",exjp:"彼の案を検討すべきだ。",deck:"h1"},
{w:"effort",jp:"努力",hook:"研究者の「エフォート率」＝仕事にかける労力の割合",ex:"Success needs effort.",exjp:"成功には努力が要る。",deck:"h1"},
{w:"opportunity",jp:"機会",hook:"オポチュニティ。チャンスのかしこまった版",ex:"This is a good opportunity to learn.",exjp:"学ぶ良い機会だ。",deck:"h1"},
{w:"available",jp:"利用できる・手に入る",hook:"AWSのアベイラビリティゾーン＝利用可能な区画",ex:"This service is available for free.",exjp:"このサービスは無料で利用できる。",deck:"h1"},
{w:"various",jp:"さまざまな",hook:"バラエティ（variety）番組＝いろいろ、の形容詞",ex:"There are various ways to learn.",exjp:"学ぶ方法はいろいろある。",deck:"h1"},
{w:"similar",jp:"似ている",hook:"類似画像検索＝similar images",ex:"My idea is similar to yours.",exjp:"私の案はあなたのと似ている。",deck:"h1"},
{w:"recent",jp:"最近の",hook:"スマホの「最近使ったアプリ」＝Recents",ex:"Recent studies show interesting results.",exjp:"最近の研究は面白い結果を示している。",deck:"h1"},
// ===== 高校標準レベル =====
{w:"reduce",jp:"減らす",hook:"3RのReduce＝ごみを減らす",ex:"We need to reduce costs.",exjp:"コストを減らす必要がある。",deck:"h2"},
{w:"benefit",jp:"利益・恩恵",hook:"福利厚生＝benefits。ベネフィット",ex:"Exercise has many benefits.",exjp:"運動には多くの利点がある。",deck:"h2"},
{w:"demand",jp:"需要・要求（する）",hook:"オンデマンド＝要求に応じて配信",ex:"Demand for AI engineers is growing.",exjp:"AIエンジニアの需要が伸びている。",deck:"h2"},
{w:"occur",jp:"起こる・発生する",hook:"エラー画面の「An error occurred」＝エラーが発生しました",ex:"The accident occurred at night.",exjp:"事故は夜に起きた。",deck:"h2"},
{w:"obtain",jp:"手に入れる・取得する",hook:"ob+tain（保持）＝手に入れて保持する。getのかたい版",ex:"You need to obtain a license.",exjp:"免許を取得する必要がある。",deck:"h2"},
{w:"maintain",jp:"維持する",hook:"メンテナンス（maintenance）＝maintainすること",ex:"It is hard to maintain motivation.",exjp:"やる気を維持するのは大変だ。",deck:"h2"},
{w:"establish",jp:"設立する・確立する",hook:"会社概要の「Established 1990」＝1990年設立",ex:"The company was established in 1990.",exjp:"その会社は1990年に設立された。",deck:"h2"},
{w:"contribute",jp:"貢献する",hook:"OSSのコントリビューター＝プロジェクトに貢献する人",ex:"He contributed to the project.",exjp:"彼はプロジェクトに貢献した。",deck:"h2"},
{w:"appreciate",jp:"感謝する・価値を分かる",hook:"ビジネス英語の定番「I appreciate your help」＝感謝します",ex:"I appreciate your help.",exjp:"助けてくれて感謝します。",deck:"h2"},
{w:"encourage",jp:"励ます・促す",hook:"en（中に入れる）+courage（勇気）＝勇気を注ぎ込む",ex:"My teacher encouraged me.",exjp:"先生が励ましてくれた。",deck:"h2"},
{w:"estimate",jp:"見積もる",hook:"開発工数のエスティメート＝見積もり",ex:"We estimated the cost.",exjp:"費用を見積もった。",deck:"h2"},
{w:"evaluate",jp:"評価する",hook:"エバリュエーション＝評価。value（価値）を測る",ex:"The teacher evaluated my essay.",exjp:"先生が私の作文を評価した。",deck:"h2"},
{w:"significant",jp:"重要な・大きな",hook:"統計の「有意差」＝significant difference",ex:"There is a significant difference.",exjp:"大きな差がある。",deck:"h2"},
{w:"sufficient",jp:"十分な",hook:"エラーの「insufficient memory」＝メモリ不足（in＝否定）",ex:"We don't have sufficient time.",exjp:"十分な時間がない。",deck:"h2"},
{w:"apparent",jp:"明らかな",hook:"appear（現れる）の親戚＝見た目に明らか",ex:"It was apparent that he was tired.",exjp:"彼が疲れているのは明らかだった。",deck:"h2"},
{w:"assume",jp:"思い込む・前提とする",hook:"仮説マッピングのassumption（思い込み・仮定）の動詞形",ex:"I assumed he was right.",exjp:"彼が正しいと思い込んでいた。",deck:"h2"},
{w:"affect",jp:"影響を与える",hook:"エフェクト（effect＝効果）の動詞側。「AがBにaffectする」",ex:"The weather affects my mood.",exjp:"天気は気分に影響する。",deck:"h2"},
{w:"determine",jp:"決定する",hook:"ターミネーター＝終わらせる者。term（限界）を定める→決定",ex:"We determined the price.",exjp:"価格を決定した。",deck:"h2"},
];
